using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using IronMeridian.Audio;
using IronMeridian.Core;
using IronMeridian.Data;
using IronMeridian.Save;

namespace IronMeridian.UI
{
    /// <summary>
    /// Single player: pick a campaign, then pick a mission from it.
    ///
    /// **Two pages in one scene, not two scenes.** The campaign board and the
    /// mission board are the same list of rows with different contents, they
    /// share a background and a music bed, and going back from one to the other
    /// has to be instant — a scene load between them would put a loading screen
    /// in the middle of a menu. Scenes here are generated by
    /// `ProjectBootstrap` from a component name, so a second scene would also
    /// mean a second bootstrap entry and a second `GameConfig` constant for a
    /// page that is one list.
    ///
    /// The class keeps its old name deliberately: `ProjectBootstrap` names the
    /// component it drops into the SinglePlayer scene, so renaming it would
    /// silently break every already-generated scene until somebody re-ran Setup
    /// Project. It just is not a placeholder any more.
    ///
    /// Missions come from <see cref="MissionLibrary"/> — the same list the map
    /// editor's MISSIONS panel writes, which is what makes an edited mission
    /// show up here with no syncing step. See docs/22-MISSIONS.md.
    /// </summary>
    public class SinglePlayerUI : MonoBehaviour
    {
        // ------------------------------------------------------------ layout
        const float BoardX = 96f, BoardWidth = 700f;
        const float TitleY = -84f;
        /// <summary>Top of the scrolling list, and the clear space under it.</summary>
        const float ListTop = -246f, ListBottom = 86f;

        /// <summary>
        /// How far the campaign and mission rows are indented from the board's
        /// own left edge, matching <c>MainMenuUI.MenuIndent</c>. The masthead
        /// stays hard against the edge and the list steps in from it, so a
        /// player walking main menu → campaigns → missions sees one board being
        /// refilled rather than three screens that happen to look similar.
        /// </summary>
        const float ListIndent = 60f;

        const float RowHeight = 96f, RowGap = 8f;
        const float StripRest = 4f, StripHover = 8f;

        /// <summary>
        /// How far a row's contents are inset from its own edges.
        ///
        /// The fill and the accent strip still run edge to edge — the strip is
        /// what marks the row, and one starting 35 px in would be a floating
        /// tick rather than a leading edge. What moves is everything you read:
        /// the glyph, both lines of text, and the caption column at the far end.
        /// </summary>
        const float RowPadLeft = 35f, RowPadRight = 20f;

        /// <summary>
        /// The right-hand inset each page uses: the base above plus 50 px on the
        /// campaign board and 40 px on a mission board.
        ///
        /// The two boards carry different things at that end — a campaign row
        /// ends in a mission count, a mission row in a date over a place — and
        /// the mission board's block is the deeper of the two, so it is given
        /// the most air to sit in.
        /// </summary>
        const float CampaignPadRight = RowPadRight + 50f;
        const float MissionPadRight = RowPadRight + 40f;

        /// <summary>Left inset of a row's glyph.</summary>
        const float GlyphX = RowPadLeft + 34f;
        /// <summary>Where a row's text column starts: clear of the glyph.</summary>
        const float TextX = RowPadLeft + 84f;

        enum Page { Campaigns, Missions }

        /// <summary>The parts of one row that change under the cursor.</summary>
        class Row
        {
            public Image Fill;
            public RectTransform Strip;
            public Image Glyph;
            public Text Label;
            public Text Detail;
            public bool Enabled = true;
        }

        Canvas _canvas;
        Text _title, _subtitle;
        RectTransform _listContent;
        Button _backButton;

        ScreenBackdrop _backdrop;
        /// <summary>The right-hand inset the page being built wants. Set by Show*.</summary>
        float _rowPadRight = RowPadRight;

        Page _page = Page.Campaigns;
        Campaign _campaign = Campaign.Europe;

        void Start()
        {
            AudioManager.Apply();
            MusicManager.Play(MusicTrack.SinglePlayerTheme);

            // Entering the campaign screen means no mission is in play. Without
            // this, backing out of a mission and going to the map editor would
            // still open the mission the player just left.
            MissionLibrary.Clear();
            // Re-read from disk: the editor may have added or changed missions
            // since this screen was last shown in the same session.
            MissionLibrary.Reload();

            _canvas = UIFactory.CreateCanvas("SinglePlayerCanvas");
            _backdrop = ScreenBackdrop.Attach(gameObject, _canvas.transform,
                BackgroundId.SinglePlayer, 0.62f);

            BuildFrame();
            ShowCampaigns();
        }

        // -------------------------------------------------------- background

        /// <summary>The artwork behind a campaign's mission board, and its hover preview.</summary>
        static BackgroundId BackgroundFor(Campaign c) => c switch
        {
            Campaign.Europe => BackgroundId.CampaignEurope,
            Campaign.Africa => BackgroundId.CampaignAfrica,
            Campaign.Asia => BackgroundId.CampaignAsia,
            Campaign.NorthAmerica => BackgroundId.CampaignNorthAmerica,
            Campaign.SouthAmerica => BackgroundId.CampaignSouthAmerica,
            Campaign.Australia => BackgroundId.CampaignAustralia,
            _ => BackgroundId.SinglePlayer
        };

        // ------------------------------------------------------------- frame

        void BuildFrame()
        {
            var field = UIFactory.CreatePanel(_canvas.transform, "BoardField",
                new Color(0.02f, 0.03f, 0.05f, 0.78f));
            field.anchorMin = new Vector2(0, 0);
            field.anchorMax = new Vector2(0, 1);
            field.pivot = new Vector2(0, 0.5f);
            field.sizeDelta = new Vector2(BoardX * 2f + BoardWidth, 0);
            field.GetComponent<Image>().raycastTarget = false;

            var edge = UIFactory.CreatePanel(field, "Edge", UiTheme.BorderStrong);
            edge.anchorMin = new Vector2(1, 0); edge.anchorMax = new Vector2(1, 1);
            edge.pivot = new Vector2(1, 0.5f);
            edge.sizeDelta = new Vector2(1, 0);
            edge.GetComponent<Image>().raycastTarget = false;

            _title = UIFactory.CreateText(_canvas.transform, "", 52, UiTheme.Text,
                TextAnchor.LowerLeft, FontStyle.Bold);
            UIFactory.Place(_title.rectTransform, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY), new Vector2(BoardWidth, 56));
            UIFactory.Fit(_title, 22);

            _subtitle = UIFactory.CreateText(_canvas.transform, "", 17, UiTheme.TextDim,
                TextAnchor.UpperLeft);
            UIFactory.Place(_subtitle.rectTransform, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY - 62f), new Vector2(BoardWidth - 20f, 58));

            var accentRule = UIFactory.CreatePanel(_canvas.transform, "AccentRule", UiTheme.Accent);
            UIFactory.Place(accentRule, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY - 128f), new Vector2(84, 3));
            accentRule.GetComponent<Image>().raycastTarget = false;

            var rule = UIFactory.CreatePanel(_canvas.transform, "Rule", UiTheme.Border);
            UIFactory.Place(rule, new Vector2(0f, 1f),
                new Vector2(BoardX + 90f, TitleY - 128f), new Vector2(BoardWidth - 90f, 1));
            rule.GetComponent<Image>().raycastTarget = false;

            // The list. Scrolls, because a campaign can hold as many missions as
            // somebody cares to add in the editor.
            var scroll = UIFactory.CreateScrollView(_canvas.transform, out _listContent,
                withScrollbar: true, autoHideScrollbar: true);
            scroll.GetComponent<Image>().color = new Color(0, 0, 0, 0);

            var srt = (RectTransform)scroll.transform;
            srt.anchorMin = new Vector2(0, 0); srt.anchorMax = new Vector2(0, 1);
            srt.pivot = new Vector2(0, 0.5f);
            srt.offsetMin = new Vector2(BoardX + ListIndent, ListBottom);
            srt.offsetMax = new Vector2(BoardX + BoardWidth, ListTop);

            var layout = _listContent.GetComponent<VerticalLayoutGroup>();
            layout.spacing = RowGap;
            layout.padding = new RectOffset(0, 0, 0, 12);

            _backButton = UIFactory.CreateBackButton(_canvas.transform, "BACK", GoBack);
        }

        // -------------------------------------------------------------- pages

        void ShowCampaigns()
        {
            _page = Page.Campaigns;
            _backdrop.SetPage(BackgroundId.SinglePlayer);
            _rowPadRight = CampaignPadRight;
            _title.text = "SINGLE PLAYER";
            _subtitle.text = "Choose a campaign. Each one is a theatre, and each mission in it is " +
                             "a piece of real ground you fight over.";
            SetBackLabel("BACK TO MAIN MENU");

            ClearList();
            foreach (var campaign in CampaignInfo.All)
            {
                var c = campaign;
                int count = MissionLibrary.OfCampaign(c).Count;

                AddRow(
                    CampaignGlyph(c),
                    CampaignInfo.DisplayName(c),
                    CampaignInfo.Blurb(c),
                    count == 1 ? "1 MISSION" : $"{count} MISSIONS",
                    null,
                    enabled: count > 0,
                    () => ShowMissions(c),
                    // The row shows you the ground before you commit to it. A
                    // campaign is a place, and a name and a blurb are a poor way
                    // to say which place.
                    preview: BackgroundFor(c));
            }
        }

        void ShowMissions(Campaign campaign)
        {
            _page = Page.Missions;
            _campaign = campaign;
            _backdrop.SetPage(BackgroundFor(campaign));
            _rowPadRight = MissionPadRight;
            _title.text = CampaignInfo.DisplayName(campaign);
            _subtitle.text = CampaignInfo.Blurb(campaign);
            SetBackLabel("BACK TO CAMPAIGNS");

            ClearList();

            var missions = MissionLibrary.OfCampaign(campaign);
            if (missions.Count == 0)
            {
                Empty("No missions in this campaign yet. Add one from the map editor's " +
                      "MISSIONS panel — Development → Map Editor.");
                return;
            }

            foreach (var mission in missions)
            {
                var m = mission;
                string detail = string.IsNullOrEmpty(m.briefing)
                    ? (string.IsNullOrEmpty(m.location) ? "—" : m.location)
                    : m.briefing;

                AddRow(UiIcons.Pin, m.name.ToUpperInvariant(), detail,
                    WhenText(m.startDateTime),
                    string.IsNullOrEmpty(m.location) ? "" : m.location.ToUpperInvariant(),
                    enabled: true,
                    () => Launch(m));
            }
        }

        /// <summary>
        /// A mission's H-hour as the board shows it: "18 MAR 2025 · 05:45".
        ///
        /// Parsed rather than sliced, so a malformed date in a hand-edited
        /// mission file degrades to itself instead of to a substring of itself.
        /// The time is worth the four characters: half these missions are
        /// fought in the dark, and the hour is the first thing that tells you.
        /// </summary>
        static string WhenText(string startDateTime)
        {
            if (string.IsNullOrWhiteSpace(startDateTime)) return "";

            if (System.DateTime.TryParseExact(startDateTime, "yyyy-MM-dd HH:mm",
                    System.Globalization.CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None, out var when))
                return when.ToString("dd MMM yyyy",
                    System.Globalization.CultureInfo.InvariantCulture).ToUpperInvariant()
                    + "  ·  " + when.ToString("HH:mm");

            return startDateTime;
        }

        /// <summary>
        /// One glyph per theatre. They are marks rather than maps — a 26 px
        /// pictogram cannot draw a continent — so each is picked for what the
        /// campaign's ground *is*: a shield for the plain everyone planned to
        /// defend, a flame for the desert, a warship for a theatre fought
        /// across water.
        /// </summary>
        static Sprite CampaignGlyph(Campaign c) => c switch
        {
            Campaign.Europe => UiIcons.Shield,
            Campaign.Africa => UiIcons.Flame,
            Campaign.Asia => UiIcons.Pin,
            Campaign.NorthAmerica => UiIcons.Layers,
            Campaign.SouthAmerica => UiIcons.Cloud,
            Campaign.Australia => UiIcons.Warship,
            _ => UiIcons.Flag
        };

        // ------------------------------------------------------------ launch

        /// <summary>
        /// Hands the mission to the Game scene and loads it behind the standard
        /// overlay. The pick is a static on <see cref="MissionLibrary"/> because
        /// Unity's scene loader takes a name and nothing else.
        /// </summary>
        void Launch(MissionDefinition mission)
        {
            // The async load leaves this screen running until the swap, so a
            // second click — or an Escape — would start a competing load. One
            // flag closes both doors.
            if (_launching) return;
            _launching = true;

            MissionLibrary.Select(mission);

            string where = string.IsNullOrEmpty(mission.location) ? mission.name : mission.location;
            SceneLoader.Load(GameConfig.SceneGame, mission.name, $"Preparing {where}");
        }

        /// <summary>True from the moment a mission is picked until the scene swaps.</summary>
        bool _launching;

        // -------------------------------------------------------------- rows

        void ClearList()
        {
            // Unparent before Destroy: destruction is deferred to end of frame,
            // so the old rows would otherwise sit in the layout beside the new
            // ones for a frame and the page would visibly jump.
            for (int i = _listContent.childCount - 1; i >= 0; i--)
            {
                var child = _listContent.GetChild(i);
                child.SetParent(null, false);
                Destroy(child.gameObject);
            }
        }

        void Empty(string message)
        {
            var t = UIFactory.CreateText(_listContent, message, 17, UiTheme.TextFaint,
                TextAnchor.UpperLeft);
            ((RectTransform)t.transform).sizeDelta = new Vector2(0, 90);
        }

        /// <summary>
        /// One selectable row: glyph, title, a line of description, and a small
        /// right-hand caption for the fact that belongs on the row rather than
        /// in the sentence — how many missions a campaign holds, where a mission
        /// is.
        /// </summary>
        /// <summary>
        /// One row: glyph, title, a line of detail, and a caption column at the
        /// right-hand end carrying one or two stacked lines.
        ///
        /// A mission's caption is **when and where** — the date it is fought on
        /// over the ground it is fought over. Both belong on the board rather
        /// than inside the mission: a campaign that spans thirty-five years is
        /// a chronology, and a list of names with no dates on it throws that
        /// away.
        /// </summary>
        void AddRow(Sprite glyph, string label, string detail, string caption, string captionSub,
            bool enabled, UnityEngine.Events.UnityAction action,
            BackgroundId? preview = null)
        {
            float padRight = _rowPadRight;
            var frame = UIFactory.CreateBorderedPanel(_listContent, "Row_" + label,
                UiTheme.Surface, UiTheme.Border);
            frame.sizeDelta = new Vector2(0, RowHeight);

            var btn = UIFactory.CreateButton(frame, "", action, new Color(0, 0, 0, 0), UiTheme.Text, 1);
            UIFactory.Stretch((RectTransform)btn.transform);
            var made = btn.GetComponentInChildren<Text>(true);
            if (made != null) made.gameObject.SetActive(false);
            btn.interactable = enabled;

            Color accent = enabled ? UiTheme.Accent : UiTheme.TextFaint;

            var strip = UIFactory.CreatePanel(frame, "Strip", accent);
            strip.anchorMin = new Vector2(0, 0); strip.anchorMax = new Vector2(0, 1);
            strip.pivot = new Vector2(0, 0.5f);
            strip.sizeDelta = new Vector2(StripRest, 0);
            strip.GetComponent<Image>().raycastTarget = false;

            var icon = UIFactory.CreateImage(frame, glyph, "Glyph");
            icon.color = accent;
            icon.raycastTarget = false;
            UIFactory.Place((RectTransform)icon.transform, new Vector2(0f, 0.5f),
                new Vector2(GlyphX, 0), new Vector2(30, 30));

            float captionWidth = string.IsNullOrEmpty(caption) ? 0f
                : string.IsNullOrEmpty(captionSub) ? 150f : 190f;
            float textWidth = BoardWidth - ListIndent - UIFactory.ScrollbarWidth
                              - TextX - padRight - 4f - captionWidth;

            var title = UIFactory.CreateText(frame, label, 24, UiTheme.Text,
                TextAnchor.MiddleLeft, FontStyle.Bold);
            UIFactory.PlaceTopLeft(title.rectTransform, TextX, 16f, textWidth, 28f);
            UIFactory.Fit(title, 15);

            var sub = UIFactory.CreateText(frame, detail, 15, UiTheme.TextDim, TextAnchor.UpperLeft);
            UIFactory.PlaceTopLeft(sub.rectTransform, TextX, 46f, textWidth, 40f);
            UIFactory.Fit(sub, 11);

            if (!string.IsNullOrEmpty(caption))
            {
                // One line sits on the row's midline; two straddle it, so the
                // pair reads as a block rather than as a line with something
                // hanging off it.
                bool stacked = !string.IsNullOrEmpty(captionSub);

                var chip = UIFactory.CreateText(frame, caption, 14,
                    enabled ? UiTheme.Accent : UiTheme.TextFaint,
                    TextAnchor.MiddleRight, FontStyle.Bold);
                chip.raycastTarget = false;
                UIFactory.Place(chip.rectTransform, new Vector2(1f, 0.5f),
                    new Vector2(-padRight, stacked ? 10 : 0), new Vector2(captionWidth, 18));
                UIFactory.Fit(chip, 9);

                if (stacked)
                {
                    var where = UIFactory.CreateText(frame, captionSub, UiTheme.FontLabel,
                        UiTheme.TextFaint, TextAnchor.MiddleRight);
                    where.raycastTarget = false;
                    UIFactory.Place(where.rectTransform, new Vector2(1f, 0.5f),
                        new Vector2(-padRight, -9), new Vector2(captionWidth, 16));
                    UIFactory.Fit(where, 9);
                }
            }

            var row = new Row
            {
                Fill = frame.Find("Fill").GetComponent<Image>(),
                Strip = strip,
                Glyph = icon,
                Label = title,
                Detail = sub,
                Enabled = enabled
            };

            // Painted by hand rather than through Button's colour tint: the tint
            // multiplies the whole row including the glyph and the strip, which
            // washes the accent out instead of lifting it.
            var trigger = frame.gameObject.AddComponent<EventTrigger>();
            AddEvent(trigger, EventTriggerType.PointerEnter, () =>
            {
                Paint(row, true);
                // A row with no preview leaves the page's picture alone rather
                // than clearing it — the mission board's artwork is already the
                // campaign's, and blanking it under the cursor would be the
                // screen flickering at every mouse movement.
                if (preview.HasValue && enabled) _backdrop.Preview(preview.Value);
            });
            AddEvent(trigger, EventTriggerType.PointerExit, () =>
            {
                Paint(row, false);
                if (preview.HasValue) _backdrop.ClearPreview();
            });
            Paint(row, false);
        }

        static void Paint(Row r, bool hover)
        {
            if (!r.Enabled)
            {
                r.Fill.color = UiTheme.Surface;
                r.Label.color = UiTheme.TextDim;
                r.Detail.color = UiTheme.TextFaint;
                return;
            }

            r.Fill.color = hover ? UiTheme.SurfaceHover : UiTheme.Surface;
            r.Strip.sizeDelta = new Vector2(hover ? StripHover : StripRest, 0);
            r.Glyph.color = hover ? Color.white : UiTheme.Accent;
            r.Label.color = hover ? Color.white : UiTheme.Text;
            r.Detail.color = hover ? UiTheme.Text : UiTheme.TextDim;
        }

        static void AddEvent(EventTrigger trigger, EventTriggerType type, System.Action callback)
        {
            var entry = new EventTrigger.Entry { eventID = type };
            entry.callback.AddListener(_ => callback());
            trigger.triggers.Add(entry);
        }

        // --------------------------------------------------------- navigation

        void SetBackLabel(string label) => UIFactory.SetBackButtonLabel(_backButton, label);

        /// <summary>One step back: missions → campaigns → main menu.</summary>
        void GoBack()
        {
            if (_page == Page.Missions) { ShowCampaigns(); return; }
            SceneManager.LoadScene(GameConfig.SceneMainMenu);
        }

        void Update()
        {
            if (_launching) return;
            if (Input.GetKeyDown(KeyCode.Escape)) GoBack();
        }
    }
}
