using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using IronMeridian.Audio;
using IronMeridian.Core;
using IronMeridian.Data;
using IronMeridian.Save;

namespace IronMeridian.UI
{
    /// <summary>
    /// Single player: pick a campaign, then pick a mission from it.
    ///
    /// **Two pages in one scene, not two scenes.** The campaign board and the
    /// mission board are the same list of rows with different contents, they
    /// share a background and a music bed, and going back from one to the other
    /// has to be instant — a scene load between them would put a loading screen
    /// in the middle of a menu. Scenes here are generated by
    /// `ProjectBootstrap` from a component name, so a second scene would also
    /// mean a second bootstrap entry and a second `GameConfig` constant for a
    /// page that is one list.
    ///
    /// The class keeps its old name deliberately: `ProjectBootstrap` names the
    /// component it drops into the SinglePlayer scene, so renaming it would
    /// silently break every already-generated scene until somebody re-ran Setup
    /// Project. It just is not a placeholder any more.
    ///
    /// Missions come from <see cref="MissionLibrary"/> — the same list the map
    /// editor's MISSIONS panel writes, which is what makes an edited mission
    /// show up here with no syncing step. See docs/22-MISSIONS.md.
    /// </summary>
    public class SinglePlayerUI : MonoBehaviour
    {
        // ------------------------------------------------------------ layout
        const float BoardX = 96f, BoardWidth = 700f;
        const float TitleY = -84f;
        /// <summary>Top of the scrolling list, and the clear space under it.</summary>
        const float ListTop = -246f, ListBottom = 86f;

        const float RowHeight = 96f, RowGap = 8f;
        const float StripRest = 4f, StripHover = 8f;
        /// <summary>Where a row's text column starts: clear of the glyph.</summary>
        const float TextX = 84f;

        enum Page { Campaigns, Missions }

        /// <summary>The parts of one row that change under the cursor.</summary>
        class Row
        {
            public Image Fill;
            public RectTransform Strip;
            public Image Glyph;
            public Text Label;
            public Text Detail;
            public bool Enabled = true;
        }

        Canvas _canvas;
        Text _title, _subtitle;
        RectTransform _listContent;
        Button _backButton;

        Page _page = Page.Campaigns;
        Campaign _campaign = Campaign.WestEurope;

        void Start()
        {
            AudioManager.Apply();
            MusicManager.Play(MusicTrack.SinglePlayerTheme);

            // Entering the campaign screen means no mission is in play. Without
            // this, backing out of a mission and going to the map editor would
            // still open the mission the player just left.
            MissionLibrary.Clear();
            // Re-read from disk: the editor may have added or changed missions
            // since this screen was last shown in the same session.
            MissionLibrary.Reload();

            _canvas = UIFactory.CreateCanvas("SinglePlayerCanvas");
            UIFactory.CreateScreenBackground(_canvas.transform, BackgroundId.SinglePlayer, 0.62f);

            BuildFrame();
            ShowCampaigns();
        }

        // ------------------------------------------------------------- frame

        void BuildFrame()
        {
            var field = UIFactory.CreatePanel(_canvas.transform, "BoardField",
                new Color(0.02f, 0.03f, 0.05f, 0.78f));
            field.anchorMin = new Vector2(0, 0);
            field.anchorMax = new Vector2(0, 1);
            field.pivot = new Vector2(0, 0.5f);
            field.sizeDelta = new Vector2(BoardX * 2f + BoardWidth, 0);
            field.GetComponent<Image>().raycastTarget = false;

            var edge = UIFactory.CreatePanel(field, "Edge", UiTheme.BorderStrong);
            edge.anchorMin = new Vector2(1, 0); edge.anchorMax = new Vector2(1, 1);
            edge.pivot = new Vector2(1, 0.5f);
            edge.sizeDelta = new Vector2(1, 0);
            edge.GetComponent<Image>().raycastTarget = false;

            _title = UIFactory.CreateText(_canvas.transform, "", 52, UiTheme.Text,
                TextAnchor.LowerLeft, FontStyle.Bold);
            UIFactory.Place(_title.rectTransform, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY), new Vector2(BoardWidth, 56));
            UIFactory.Fit(_title, 22);

            _subtitle = UIFactory.CreateText(_canvas.transform, "", 17, UiTheme.TextDim,
                TextAnchor.UpperLeft);
            UIFactory.Place(_subtitle.rectTransform, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY - 62f), new Vector2(BoardWidth - 20f, 58));

            var accentRule = UIFactory.CreatePanel(_canvas.transform, "AccentRule", UiTheme.Accent);
            UIFactory.Place(accentRule, new Vector2(0f, 1f),
                new Vector2(BoardX, TitleY - 128f), new Vector2(84, 3));
            accentRule.GetComponent<Image>().raycastTarget = false;

            var rule = UIFactory.CreatePanel(_canvas.transform, "Rule", UiTheme.Border);
            UIFactory.Place(rule, new Vector2(0f, 1f),
                new Vector2(BoardX + 90f, TitleY - 128f), new Vector2(BoardWidth - 90f, 1));
            rule.GetComponent<Image>().raycastTarget = false;

            // The list. Scrolls, because a campaign can hold as many missions as
            // somebody cares to add in the editor.
            var scroll = UIFactory.CreateScrollView(_canvas.transform, out _listContent,
                withScrollbar: true);
            scroll.GetComponent<Image>().color = new Color(0, 0, 0, 0);

            var srt = (RectTransform)scroll.transform;
            srt.anchorMin = new Vector2(0, 0); srt.anchorMax = new Vector2(0, 1);
            srt.pivot = new Vector2(0, 0.5f);
            srt.offsetMin = new Vector2(BoardX, ListBottom);
            srt.offsetMax = new Vector2(BoardX + BoardWidth, ListTop);

            var layout = _listContent.GetComponent<VerticalLayoutGroup>();
            layout.spacing = RowGap;
            layout.padding = new RectOffset(0, 0, 0, 12);

            _backButton = UIFactory.CreateBackButton(_canvas.transform, "BACK", GoBack,
                new Vector2(0f, 0f), new Vector2(BoardX, 24f), new Vector2(320, 56));
        }

        // -------------------------------------------------------------- pages

        void ShowCampaigns()
        {
            _page = Page.Campaigns;
            _title.text = "SINGLE PLAYER";
            _subtitle.text = "Choose a campaign. Each one is a theatre, and each mission in it is " +
                             "a piece of real ground you fight over.";
            SetBackLabel("BACK TO MAIN MENU");

            ClearList();
            foreach (var campaign in CampaignInfo.All)
            {
                var c = campaign;
                int count = MissionLibrary.OfCampaign(c).Count;

                AddRow(
                    CampaignGlyph(c),
                    CampaignInfo.DisplayName(c),
                    CampaignInfo.Blurb(c),
                    count == 1 ? "1 MISSION" : $"{count} MISSIONS",
                    enabled: count > 0,
                    () => ShowMissions(c));
            }
        }

        void ShowMissions(Campaign campaign)
        {
            _page = Page.Missions;
            _campaign = campaign;
            _title.text = CampaignInfo.DisplayName(campaign);
            _subtitle.text = CampaignInfo.Blurb(campaign);
            SetBackLabel("BACK TO CAMPAIGNS");

            ClearList();

            var missions = MissionLibrary.OfCampaign(campaign);
            if (missions.Count == 0)
            {
                Empty("No missions in this campaign yet. Add one from the map editor's " +
                      "MISSIONS panel — Testing → Map Editor.");
                return;
            }

            foreach (var mission in missions)
            {
                var m = mission;
                string detail = string.IsNullOrEmpty(m.briefing)
                    ? (string.IsNullOrEmpty(m.location) ? "—" : m.location)
                    : m.briefing;

                AddRow(UiIcons.Pin, m.name.ToUpperInvariant(), detail,
                    string.IsNullOrEmpty(m.location) ? "" : m.location.ToUpperInvariant(),
                    enabled: true,
                    () => Launch(m));
            }
        }

        static Sprite CampaignGlyph(Campaign c) => c switch
        {
            Campaign.WestEurope => UiIcons.Shield,
            Campaign.EastEurope => UiIcons.Flag,
            _ => UiIcons.Layers
        };

        // ------------------------------------------------------------ launch

        /// <summary>
        /// Hands the mission to the Game scene and loads it behind the standard
        /// overlay. The pick is a static on <see cref="MissionLibrary"/> because
        /// Unity's scene loader takes a name and nothing else.
        /// </summary>
        void Launch(MissionDefinition mission)
        {
            // The async load leaves this screen running until the swap, so a
            // second click — or an Escape — would start a competing load. One
            // flag closes both doors.
            if (_launching) return;
            _launching = true;

            MissionLibrary.Select(mission);

            string where = string.IsNullOrEmpty(mission.location) ? mission.name : mission.location;
            SceneLoader.Load(GameConfig.SceneGame, mission.name, $"Preparing {where}");
        }

        /// <summary>True from the moment a mission is picked until the scene swaps.</summary>
        bool _launching;

        // -------------------------------------------------------------- rows

        void ClearList()
        {
            // Unparent before Destroy: destruction is deferred to end of frame,
            // so the old rows would otherwise sit in the layout beside the new
            // ones for a frame and the page would visibly jump.
            for (int i = _listContent.childCount - 1; i >= 0; i--)
            {
                var child = _listContent.GetChild(i);
                child.SetParent(null, false);
                Destroy(child.gameObject);
            }
        }

        void Empty(string message)
        {
            var t = UIFactory.CreateText(_listContent, message, 17, UiTheme.TextFaint,
                TextAnchor.UpperLeft);
            ((RectTransform)t.transform).sizeDelta = new Vector2(0, 90);
        }

        /// <summary>
        /// One selectable row: glyph, title, a line of description, and a small
        /// right-hand caption for the fact that belongs on the row rather than
        /// in the sentence — how many missions a campaign holds, where a mission
        /// is.
        /// </summary>
        void AddRow(Sprite glyph, string label, string detail, string caption,
            bool enabled, UnityEngine.Events.UnityAction action)
        {
            var frame = UIFactory.CreateBorderedPanel(_listContent, "Row_" + label,
                UiTheme.Surface, UiTheme.Border);
            frame.sizeDelta = new Vector2(0, RowHeight);

            var btn = UIFactory.CreateButton(frame, "", action, new Color(0, 0, 0, 0), UiTheme.Text, 1);
            UIFactory.Stretch((RectTransform)btn.transform);
            var made = btn.GetComponentInChildren<Text>(true);
            if (made != null) made.gameObject.SetActive(false);
            btn.interactable = enabled;

            Color accent = enabled ? UiTheme.Accent : UiTheme.TextFaint;

            var strip = UIFactory.CreatePanel(frame, "Strip", accent);
            strip.anchorMin = new Vector2(0, 0); strip.anchorMax = new Vector2(0, 1);
            strip.pivot = new Vector2(0, 0.5f);
            strip.sizeDelta = new Vector2(StripRest, 0);
            strip.GetComponent<Image>().raycastTarget = false;

            var icon = UIFactory.CreateImage(frame, glyph, "Glyph");
            icon.color = accent;
            icon.raycastTarget = false;
            UIFactory.Place((RectTransform)icon.transform, new Vector2(0f, 0.5f),
                new Vector2(34, 0), new Vector2(30, 30));

            float captionWidth = string.IsNullOrEmpty(caption) ? 0f : 150f;
            float textWidth = BoardWidth - UIFactory.ScrollbarWidth - TextX - 24f - captionWidth;

            var title = UIFactory.CreateText(frame, label, 24, UiTheme.Text,
                TextAnchor.MiddleLeft, FontStyle.Bold);
            UIFactory.PlaceTopLeft(title.rectTransform, TextX, 16f, textWidth, 28f);
            UIFactory.Fit(title, 15);

            var sub = UIFactory.CreateText(frame, detail, 15, UiTheme.TextDim, TextAnchor.UpperLeft);
            UIFactory.PlaceTopLeft(sub.rectTransform, TextX, 46f, textWidth, 40f);
            UIFactory.Fit(sub, 11);

            if (!string.IsNullOrEmpty(caption))
            {
                var chip = UIFactory.CreateText(frame, caption, UiTheme.FontLabel,
                    UiTheme.TextFaint, TextAnchor.MiddleRight);
                chip.raycastTarget = false;
                UIFactory.Place(chip.rectTransform, new Vector2(1f, 0.5f),
                    new Vector2(-22, 0), new Vector2(captionWidth, 18));
                UIFactory.Fit(chip, 9);
            }

            var row = new Row
            {
                Fill = frame.Find("Fill").GetComponent<Image>(),
                Strip = strip,
                Glyph = icon,
                Label = title,
                Detail = sub,
                Enabled = enabled
            };

            // Painted by hand rather than through Button's colour tint: the tint
            // multiplies the whole row including the glyph and the strip, which
            // washes the accent out instead of lifting it.
            var trigger = frame.gameObject.AddComponent<EventTrigger>();
            AddEvent(trigger, EventTriggerType.PointerEnter, () => Paint(row, true));
            AddEvent(trigger, EventTriggerType.PointerExit, () => Paint(row, false));
            Paint(row, false);
        }

        static void Paint(Row r, bool hover)
        {
            if (!r.Enabled)
            {
                r.Fill.color = UiTheme.Surface;
                r.Label.color = UiTheme.TextDim;
                r.Detail.color = UiTheme.TextFaint;
                return;
            }

            r.Fill.color = hover ? UiTheme.SurfaceHover : UiTheme.Surface;
            r.Strip.sizeDelta = new Vector2(hover ? StripHover : StripRest, 0);
            r.Glyph.color = hover ? Color.white : UiTheme.Accent;
            r.Label.color = hover ? Color.white : UiTheme.Text;
            r.Detail.color = hover ? UiTheme.Text : UiTheme.TextDim;
        }

        static void AddEvent(EventTrigger trigger, EventTriggerType type, System.Action callback)
        {
            var entry = new EventTrigger.Entry { eventID = type };
            entry.callback.AddListener(_ => callback());
            trigger.triggers.Add(entry);
        }

        // --------------------------------------------------------- navigation

        void SetBackLabel(string label) => UIFactory.SetBackButtonLabel(_backButton, label);

        /// <summary>One step back: missions → campaigns → main menu.</summary>
        void GoBack()
        {
            if (_page == Page.Missions) { ShowCampaigns(); return; }
            SceneManager.LoadScene(GameConfig.SceneMainMenu);
        }

        void Update()
        {
            if (_launching) return;
            if (Input.GetKeyDown(KeyCode.Escape)) GoBack();
        }
    }
}
