using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Data;
using IronMeridian.Lines;
using IronMeridian.Map;

namespace IronMeridian.Units
{
    /// <summary>
    /// The shape of an operation, drawn on the map. **Nothing here executes.**
    ///
    /// **Why a planner that does nothing is worth having.** Every other control
    /// on the order bar makes a formation do something now. An operation is not
    /// a sequence of those: it is a main effort, the supporting efforts that
    /// make it possible, and the line everything falls back to if it does not
    /// work — decided before any of it is ordered, and useful precisely because
    /// it is written down where it can be looked at while the fighting is
    /// happening. A commander who cannot draw the plan has to hold it in their
    /// head and re-derive it every time they look at the map.
    ///
    /// **Two axes, and the difference between them is the whole point.** The
    /// main attack is the decisive effort — where the operation is won — and is
    /// drawn heavy and hot. A supporting attack fixes, diverts or protects, and
    /// is drawn lighter and cooler. Two identical arrows would be two arrows; a
    /// weighted pair is a plan.
    ///
    /// **The retreat line is not here.** It is a movement contingency
    /// (<see cref="MoveTask.Retreat"/>), because unlike the two axes it is a
    /// thing a formation actually carries out. Putting a copy of it in the
    /// planner would be two controls that look like planning and behave
    /// differently — so the planner's third entry calls the same order.
    ///
    /// Every graphic is ordinary map data through <see cref="LineManager"/>, so
    /// a plan survives a save/load. Ids are prefixed <c>plan-</c>, which keeps
    /// them clear of the <c>task-</c> areas and the <c>sector-</c> graphics that
    /// "clear tactical graphics" regenerates.
    ///
    /// See docs/15-COMBAT-ORDERS.md.
    /// </summary>
    public class PlannerSystem : MonoBehaviour
    {
        public System.Action<string> Flash;

        /// <summary>Half-width of an axis at its base, as a fraction of its length.</summary>
        const double MainWidthFraction = 0.16, SupportingWidthFraction = 0.09;
        /// <summary>Where the arrowhead starts, as a fraction of the axis's length.</summary>
        const double HeadStartFraction = 0.74;
        /// <summary>How far the head flares beyond the shaft, as a multiple of the shaft's half-width.</summary>
        const double HeadFlare = 2.1;
        /// <summary>Line width on the map, metres. The main effort is visibly the heavier one.</summary>
        const float MainWidthM = 140f, SupportingWidthM = 70f;

        static readonly Color MainTint = new Color(1.00f, 0.45f, 0.25f);
        static readonly Color SupportingTint = new Color(0.95f, 0.78f, 0.42f);

        LineManager _lines;

        public void Init(LineManager lines) => _lines = lines;

        /// <summary>
        /// Draws an axis from a formation to a point. Replaces that formation's
        /// previous axis of the same kind — a unit has one main effort, and two
        /// arrows out of one counter would be a plan that had not been decided.
        /// </summary>
        public bool Draw(UnitActor from, PlanKind kind, double lat, double lon)
        {
            if (from == null || !from.IsAlive || _lines == null)
            {
                Flash?.Invoke("Select the formation the axis starts from.");
                return false;
            }

            double km = GeoUtils.DistanceKm(from.State.latitude, from.State.longitude, lat, lon);
            if (km < 0.2)
            {
                Flash?.Invoke("Draw the axis onto ground away from the formation.");
                return false;
            }

            bool main = kind == PlanKind.MainAttack;
            string id = $"plan-{from.State.instanceId}-{(main ? "main" : "supporting")}";
            string designation = Designation(from);

            _lines.Upsert(new MapLineData
            {
                id = id,
                // A phase line rather than a battle position: this is a control
                // measure, not ground anybody is standing on.
                kind = LineKind.PhaseLine.ToString(),
                team = from.State.TeamEnum.ToString(),
                is3D = true,
                autoGenerated = true,
                points = Axis(from.State.latitude, from.State.longitude, lat, lon,
                    main ? MainWidthFraction : SupportingWidthFraction),
                label = main
                    ? $"MAIN ATTACK — {designation.ToUpperInvariant()}"
                    : $"SUPPORTING — {designation.ToUpperInvariant()}",
                colorHex = "#" + ColorUtility.ToHtmlStringRGB(main ? MainTint : SupportingTint),
                widthMeters = main ? MainWidthM : SupportingWidthM,
                // Broken, because that is what a control measure that has not
                // happened yet is drawn as. The whole planner is on-order.
                planned = true
            });

            Flash?.Invoke(main
                ? $"Main attack drawn — {designation}, {km:0.#} km axis."
                : $"Supporting attack drawn — {designation}, {km:0.#} km axis.");
            return true;
        }

        /// <summary>Drops both axes for one formation.</summary>
        public void ClearFor(UnitActor unit)
        {
            if (unit == null || _lines == null) return;
            _lines.RemoveAutoGenerated($"plan-{unit.State.instanceId}-");
        }

        /// <summary>Drops every plan on the map. Used when a scenario is reloaded or reset.</summary>
        public void ClearAll() => _lines?.RemoveAutoGenerated("plan-");

        // ---------------------------------------------------------- geometry

        /// <summary>
        /// A closed arrow from one point to another: a parallel shaft, a flared
        /// head, and back down the other side.
        ///
        /// Built as an outline rather than a filled mesh because everything on
        /// this map is a draped polyline — an arrow that was a mesh would be the
        /// one graphic that did not follow the terrain, and over a ridge that
        /// difference is the whole picture.
        /// </summary>
        static List<GeoPoint> Axis(double fromLat, double fromLon, double toLat, double toLon,
            double widthFraction)
        {
            double km = GeoUtils.DistanceKm(fromLat, fromLon, toLat, toLon);
            float bearing = GeoUtils.BearingDeg(fromLat, fromLon, toLat, toLon);
            double half = System.Math.Max(0.08, km * widthFraction * 0.5);
            double headStart = km * HeadStartFraction;

            var pts = new List<GeoPoint>(8);

            // Down the left side of the shaft, out to the head's shoulder…
            pts.Add(Offset(fromLat, fromLon, bearing, 0.0, -half));
            pts.Add(Offset(fromLat, fromLon, bearing, headStart, -half));
            pts.Add(Offset(fromLat, fromLon, bearing, headStart, -half * HeadFlare));
            // …to the point…
            pts.Add(new GeoPoint { latitude = toLat, longitude = toLon });
            // …and back down the right.
            pts.Add(Offset(fromLat, fromLon, bearing, headStart, half * HeadFlare));
            pts.Add(Offset(fromLat, fromLon, bearing, headStart, half));
            pts.Add(Offset(fromLat, fromLon, bearing, 0.0, half));
            pts.Add(new GeoPoint { latitude = pts[0].latitude, longitude = pts[0].longitude });

            return pts;
        }

        /// <summary>A point <paramref name="alongKm"/> up the axis and <paramref name="acrossKm"/> off it.</summary>
        static GeoPoint Offset(double lat, double lon, float bearing, double alongKm, double acrossKm)
        {
            double aLat = lat, aLon = lon;
            if (System.Math.Abs(alongKm) > 1e-6)
                GeoUtils.Destination(lat, lon, bearing, alongKm, out aLat, out aLon);
            if (System.Math.Abs(acrossKm) > 1e-6)
                GeoUtils.Destination(aLat, aLon, bearing + 90.0, acrossKm, out aLat, out aLon);
            return new GeoPoint { latitude = aLat, longitude = aLon };
        }

        static string Designation(UnitActor u) =>
            string.IsNullOrEmpty(u.State.customName) ? u.Def.name : u.State.customName;
    }
}
