using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Data;

namespace IronMeridian.Models
{
    /// <summary>
    /// One 3D model entry: where to load it from and how to frame and animate it.
    /// Keep this in step with docs/09-3D-MODELS.md.
    /// </summary>
    public class UnitModelDef
    {
        /// <summary>Resources path of the prefab, generated by Tools > Iron Meridian > Install Unit Models.</summary>
        public string resourcePath;

        /// <summary>Human name of the source asset, for the docs and for log messages.</summary>
        public string sourceAsset;

        /// <summary>Legacy clip played when the model is just standing there.</summary>
        public string idleClip = ModelClips.CombatIdle;

        /// <summary>Multiplier applied after automatic bounds framing — nudge only if a model sits oddly.</summary>
        public float framing = 1f;
    }

    /// <summary>Names the game uses for animation states, independent of the clip's file name.</summary>
    public static class ModelClips
    {
        public const string CombatIdle = "combat_idle";
        public const string CombatRun = "combat_run";
        public const string CombatShoot = "combat_shoot";
    }

    /// <summary>
    /// Resolves a unit definition to the 3D model that represents it.
    ///
    /// Only one model is imported so far (the Low Poly Soldiers demo rifleman),
    /// so every ground unit currently shares it and drones have none. As real
    /// models arrive, add them to <see cref="Models"/> and override per unit id
    /// in <see cref="Overrides"/> — call sites do not change.
    /// </summary>
    public static class UnitModelLibrary
    {
        public const string SoldierRifleman = "soldier_rifleman";

        static readonly Dictionary<string, UnitModelDef> Models = new Dictionary<string, UnitModelDef>
        {
            [SoldierRifleman] = new UnitModelDef
            {
                resourcePath = "Models/Soldier_Rifleman",
                sourceAsset = "Low Poly Soldiers Demo — Soldier_demo.FBX",
                idleClip = ModelClips.CombatIdle,
                framing = 1f
            }
        };

        /// <summary>Per-unit-id model assignments. Anything not listed falls back to <see cref="DefaultFor"/>.</summary>
        static readonly Dictionary<string, string> Overrides = new Dictionary<string, string>();

        public static UnitModelDef Get(string modelId) =>
            modelId != null && Models.TryGetValue(modelId, out var def) ? def : null;

        /// <summary>The model that represents this unit type, or null when none exists yet.</summary>
        public static UnitModelDef Resolve(UnitDefinition unit)
        {
            if (unit == null) return null;
            if (Overrides.TryGetValue(unit.id, out string id)) return Get(id);
            return Get(DefaultFor(unit));
        }

        /// <summary>
        /// Fallback assignment while the model library is thin: a soldier stands
        /// in for any ground formation. Drones get nothing rather than a
        /// misleading infantryman.
        /// </summary>
        static string DefaultFor(UnitDefinition unit) =>
            unit.Category == UnitCategory.Drone ? null : SoldierRifleman;

        /// <summary>Every model in the library — used by the installer and the docs check.</summary>
        public static IEnumerable<UnitModelDef> All => Models.Values;
    }
}
