using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Data;

namespace IronMeridian.Models
{
    /// <summary>
    /// One 3D model entry: where to load it from and how to frame and animate it.
    /// Keep this in step with docs/09-3D-MODELS.md.
    /// </summary>
    public class UnitModelDef
    {
        /// <summary>Resources path of the prefab, generated by Tools > Iron Meridian > Install Unit Models.</summary>
        public string resourcePath;

        /// <summary>Human name of the source asset, for the docs and for log messages.</summary>
        public string sourceAsset;

        /// <summary>
        /// File names the installer will accept for the source mesh, without
        /// extension, in order of preference.
        ///
        /// A list rather than one name because asset packs rename their meshes
        /// between versions and none of these are ours. The installer takes the
        /// first that exists and names the rest in its log when it finds none,
        /// so adapting to a pack's actual naming is a one-line edit here rather
        /// than a hunt through the installer.
        /// </summary>
        public string[] sourceCandidates = System.Array.Empty<string>();

        /// <summary>Legacy clip played when the model is just standing there; null for static props.</summary>
        public string idleClip = ModelClips.CombatIdle;

        /// <summary>
        /// False for vehicles and props, which ship as static meshes. The
        /// installer skips the Legacy-rig conversion for them — forcing a rig
        /// type onto a mesh with no skeleton achieves nothing and reimports the
        /// whole pack for no reason.
        /// </summary>
        public bool animated = true;

        /// <summary>Multiplier applied after automatic bounds framing — nudge only if a model sits oddly.</summary>
        public float framing = 1f;

        /// <summary>
        /// Id in <see cref="ProceduralModels"/> for a model the project builds
        /// itself, or null for one that comes from an imported pack.
        ///
        /// A procedural entry has no source FBX and no prefab: the installer
        /// skips it, and <see cref="UnitModelLibrary.CreateInstance"/> builds it
        /// on demand. That is the point — it cannot be missing, because there is
        /// no pack to fail to import.
        /// </summary>
        public string proceduralId;

        public bool IsProcedural => !string.IsNullOrEmpty(proceduralId);
    }

    /// <summary>Names the game uses for animation states, independent of the clip's file name.</summary>
    public static class ModelClips
    {
        public const string CombatIdle = "combat_idle";
        public const string CombatRun = "combat_run";
        public const string CombatShoot = "combat_shoot";
    }

    /// <summary>
    /// Resolves a unit definition to the 3D model that represents it.
    ///
    /// The rifleman stands in for any ground formation that has nothing more
    /// specific; the entries below override that for the unit types whose own
    /// equipment has been imported. Drones deliberately get nothing rather than
    /// a misleading infantryman.
    ///
    /// A model listed here whose pack is **not imported** resolves normally and
    /// the preview says which prefab is missing and how to build it — rather
    /// than quietly showing a soldier where a Leopard should be. The pack each
    /// entry needs is named in <c>sourceAsset</c> and in docs/09-3D-MODELS.md.
    /// </summary>
    public static class UnitModelLibrary
    {
        public const string SoldierRifleman = "soldier_rifleman";
        public const string AirDefenceRadar = "air_defence_radar";
        public const string FieldArtillery = "field_artillery";
        public const string SurfaceToAirMissile = "sam_launcher";
        public const string MilitaryTruck = "military_truck";
        public const string MainBattleTank = "main_battle_tank";
        public const string ScoutCar = "scout_car";
        public const string StealthBomber = "stealth_bomber";
        public const string AttackHelicopter = "attack_helicopter";
        public const string StrikeFighter = "strike_fighter";
        public const string KamikazeDrone = "kamikaze_drone";
        public const string ShahedDrone = "shahed_drone";
        /// <summary>
        /// The airlifter that flies a supply drop — docs/29-AIR-SUPPLY.md.
        ///
        /// Deliberately *not* called "transport_aircraft": that string is
        /// already a **unit type** in units.json, and one identifier meaning
        /// both a model and a formation is how a lookup ends up pointing at the
        /// wrong one of them.
        /// </summary>
        public const string TransportAircraft = "airlift_transport";
        /// <summary>One palletised load under canopy, as dropped by the above.</summary>
        public const string SupplyBundle = "supply_bundle";
        public const string ReconDrone = "recon_drone";

        // The six logistic installations — docs/26-LOGISTICS.md. They are named
        // "..._site" rather than after the kind alone because "supply_depot" is
        // a **LogisticsKind**, and one identifier meaning both a model and a
        // catalogue row is how a lookup ends up pointing at the wrong one — the
        // same trap TransportAircraft above is named around.
        public const string SupplyDepotSite = ProceduralModels.SupplyDepotSite;
        public const string SupplyPointSite = ProceduralModels.SupplyPointSite;
        public const string FuelPointSite = ProceduralModels.FuelPointSite;
        public const string AmmoPointSite = ProceduralModels.AmmoPointSite;
        public const string RepairPointSite = ProceduralModels.RepairPointSite;
        public const string MedicalPointSite = ProceduralModels.MedicalPointSite;

        static readonly Dictionary<string, UnitModelDef> Models = new Dictionary<string, UnitModelDef>
        {
            [SoldierRifleman] = new UnitModelDef
            {
                resourcePath = "Models/Soldier_Rifleman",
                sourceAsset = "Low Poly Soldiers Demo — Soldier_demo.FBX",
                sourceCandidates = new[] { "Soldier_demo" },
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            [AirDefenceRadar] = new UnitModelDef
            {
                resourcePath = "Models/AirDefenceRadar",
                sourceAsset = "Anti-Air Defense Radar",
                sourceCandidates = new[]
                {
                    "Anti_Air_Defense_Radar", "AntiAirDefenseRadar", "AntiAirRadar", "Radar"
                },
                idleClip = null,
                animated = false
            },

            [FieldArtillery] = new UnitModelDef
            {
                resourcePath = "Models/FieldArtillery",
                sourceAsset = "Military Prop Pack: Defense",
                sourceCandidates = new[]
                {
                    // The pack ships one combined mesh named after the pack
                    // itself rather than after the gun in it.
                    "Defensive_props",
                    "Howitzer", "Artillery", "Field_Gun", "Cannon", "AntiTankGun"
                },
                idleClip = null,
                animated = false
            },

            [SurfaceToAirMissile] = new UnitModelDef
            {
                resourcePath = "Models/SamLauncher",
                sourceAsset = "Homing Missile",
                sourceCandidates = new[]
                {
                    // The Homing Missile pack's mesh is a sheet of several
                    // missiles, named for the sheet rather than for any one of them.
                    "Missiles_Pack",
                    "HomingMissile", "Homing_Missile", "Missile", "Rocket"
                },
                idleClip = null,
                animated = false,
                // A missile is long and thin; the bounds fit would otherwise put
                // the camera close enough to crop the fins.
                framing = 1.25f
            },

            [MilitaryTruck] = new UnitModelDef
            {
                resourcePath = "Models/MilitaryTruck",
                sourceAsset = "ZIL-130 Military Truck",
                sourceCandidates = new[]
                {
                    "ZIL-130", "ZIL130", "Zil_130", "ZIL_130", "Zil130"
                },
                idleClip = null,
                animated = false
            },

            [MainBattleTank] = new UnitModelDef
            {
                resourcePath = "Models/Leopard2",
                sourceAsset = "Tank Leopard 2",
                sourceCandidates = new[]
                {
                    "Leopard2", "Leopard_2", "Leopard2A6", "Leopard2A4", "Leopard"
                },
                idleClip = null,
                animated = false
            },

            [ScoutCar] = new UnitModelDef
            {
                resourcePath = "Models/ScoutCar",
                sourceAsset = "M3A1 Scout Car",
                sourceCandidates = new[]
                {
                    // Roofed variant first: the pack ships both, and a scout car
                    // with its roof on reads better as a counter at map scale.
                    "WW2_M3A1_Scout_Car", "WW2_M3A1_Scout_Car_NoRoof",
                    "M3A1", "M3A1_Scout_Car", "M3A1ScoutCar", "ScoutCar"
                },
                idleClip = null,
                animated = false
            },

            // Flown by AirStrikeSystem rather than deployed. It has no entry in
            // Overrides below because no unit type is a B-2 — the strike
            // airframes are picked from AirStrikeCatalog, not from the
            // catalogue. It is here because the library is the only sanctioned
            // way to reach a model prefab (golden rule 10), and because the
            // installer builds its prefab from this list.
            [StealthBomber] = new UnitModelDef
            {
                resourcePath = "Models/StealthBomber",
                sourceAsset = "Hessburg — Stealth Bomber (Built-In)",
                sourceCandidates = new[]
                {
                    "Stealth_Bomber", "StealthBomber", "Stealth Bomber", "B2", "B-2"
                },
                idleClip = null,
                // A flying wing with no moving surfaces. Its flight is animated
                // in code by BomberRun, not by a clip.
                animated = false
            },

            // The three below serve double duty: AirStrikeSystem and
            // UavStrikeSystem fly them, and the Air/Drone unit types in the
            // catalogue are represented by them. The helicopter and the drone
            // have their rotors as separate meshes in the source FBX, which is
            // what lets RotorSpinner turn them without any rig or clip.
            [AttackHelicopter] = new UnitModelDef
            {
                resourcePath = "Models/AttackHelicopter",
                sourceAsset = "RTS Modern Combat Vehicle Pack Free — MSH_N2",
                sourceCandidates = new[] { "MSH_N2_LE", "MSH_N2" },
                idleClip = null,
                animated = false
            },

            [StrikeFighter] = new UnitModelDef
            {
                resourcePath = "Models/StrikeFighter",
                sourceAsset = "RTS Modern Combat Vehicle Pack Free — FA_N26",
                sourceCandidates = new[] { "FA_N26_LE", "FA_N26" },
                idleClip = null,
                animated = false
            },

            // Built in code, not imported. The pack this used to come from was
            // removed from the project; rather than swap in another borrowed
            // quadcopter, the game now owns its loitering munition outright —
            // see ProceduralModels for the geometry and the runtime clip.
            [KamikazeDrone] = new UnitModelDef
            {
                resourcePath = null,
                sourceAsset = "Iron Meridian — built in code (ProceduralModels)",
                proceduralId = ProceduralModels.KamikazeDrone,
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            // Also built in code, and for the same reason as the loitering
            // munition above: the one drone whose job is to *look* has no pack
            // behind it and cannot lose one. Its twin-boom silhouette and its
            // scanning sensor turret are the whole model — see ProceduralModels.
            [ReconDrone] = new UnitModelDef
            {
                resourcePath = null,
                sourceAsset = "Iron Meridian — built in code (ProceduralModels)",
                proceduralId = ProceduralModels.ReconDrone,
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            // The airlifter that flies a supply drop, and the load it drops.
            // Both built in code for the same reason as the drones above: a
            // supply run must not be able to lose its aeroplane to a pack
            // somebody removed — see docs/29-AIR-SUPPLY.md.
            [TransportAircraft] = new UnitModelDef
            {
                resourcePath = null,
                sourceAsset = "Iron Meridian — built in code (ProceduralModels)",
                proceduralId = ProceduralModels.TransportAircraft,
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            [SupplyBundle] = new UnitModelDef
            {
                resourcePath = null,
                sourceAsset = "Iron Meridian — built in code (ProceduralModels)",
                proceduralId = ProceduralModels.SupplyBundle,
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            // --- the rear area (docs/26-LOGISTICS.md) ---
            //
            // Six installations, all built in code. Procedural for the same
            // reason the drones are — a scenario's logistics must not be able to
            // vanish with an asset pack — and *static* because they are places
            // rather than vehicles: nothing on a depot moves at the scale this
            // map is played at, and a shed with an idle clip would read as an
            // earthquake. See ProceduralModels.Logistics.cs.
            [SupplyDepotSite] = Installation(SupplyDepotSite, "Supply depot — warehouse, dock and container park"),
            [SupplyPointSite] = Installation(SupplyPointSite, "Supply point — pallets under canopies on a graded pad"),
            [FuelPointSite] = Installation(FuelPointSite, "Fuel point — bunded bulk tank and dispensing gantry"),
            [AmmoPointSite] = Installation(AmmoPointSite, "Ammunition point — three revetted bays, separated"),
            [RepairPointSite] = Installation(RepairPointSite, "Repair point — gantry over a stripped hull"),
            [MedicalPointSite] = Installation(MedicalPointSite, "Medical point — hospital tents, ambulance, landing point"),

            [ShahedDrone] = new UnitModelDef
            {
                resourcePath = "Models/ShahedDrone",
                sourceAsset = "ALSTRA INFINITE — Kamikaze Drones PolyPack Starter",
                sourceCandidates = new[]
                {
                    // The animated variant first: the pack ships a rigged one and
                    // a static one under near-identical names, and the rigged
                    // mesh is the one worth having in flight.
                    "StarterAsset_KamikazeDroneV1",
                    "StarterAsset_Static_KamikazeDroneV1"
                },
                idleClip = null,
                animated = false
            }
        };

        /// <summary>
        /// One logistic installation's row. A shared shape rather than six
        /// near-identical literals: every installation is procedural, static and
        /// unframed, and the only thing that differs between them is which
        /// builder runs and what the docs call it.
        /// </summary>
        static UnitModelDef Installation(string id, string description) => new UnitModelDef
        {
            resourcePath = null,
            sourceAsset = "Iron Meridian — built in code (ProceduralModels). " + description,
            proceduralId = id,
            idleClip = null,
            animated = false
        };

        /// <summary>
        /// Per-unit-id model assignments. Anything not listed falls back to
        /// <see cref="DefaultFor"/>. One model can serve several unit types —
        /// a truck is a truck whether it is carrying supplies or people.
        /// </summary>
        static readonly Dictionary<string, string> Overrides = new Dictionary<string, string>
        {
            // --- sensors ---
            ["ad_radar"] = AirDefenceRadar,
            ["air_defence"] = AirDefenceRadar,
            ["air_surveillance_radar"] = AirDefenceRadar,
            ["surveillance_radar"] = AirDefenceRadar,
            ["counter_battery_radar"] = AirDefenceRadar,
            ["target_acquisition"] = AirDefenceRadar,

            // --- guns ---
            ["artillery"] = FieldArtillery,
            ["self_propelled_artillery"] = FieldArtillery,
            ["towed_artillery"] = FieldArtillery,
            ["rocket_artillery"] = FieldArtillery,
            ["mortar"] = FieldArtillery,
            ["spaag"] = FieldArtillery,

            // --- missiles on launchers ---
            ["sam"] = SurfaceToAirMissile,
            ["mrad"] = SurfaceToAirMissile,
            ["lrad"] = SurfaceToAirMissile,
            ["missile_defence"] = SurfaceToAirMissile,
            ["shorad"] = SurfaceToAirMissile,
            ["surface_to_surface_missile"] = SurfaceToAirMissile,
            ["deep_precision_strike"] = SurfaceToAirMissile,
            ["coastal_defence_missile"] = SurfaceToAirMissile,

            // --- wheels ---
            ["transport"] = MilitaryTruck,
            ["logistics"] = MilitaryTruck,
            ["supply"] = MilitaryTruck,
            ["ammunition"] = MilitaryTruck,
            ["fuel_pol"] = MilitaryTruck,
            ["water_supply"] = MilitaryTruck,
            ["recovery"] = MilitaryTruck,
            ["medevac"] = MilitaryTruck,
            ["bridging"] = MilitaryTruck,
            ["movement_control"] = MilitaryTruck,

            // --- tracks ---
            ["armour"] = MainBattleTank,
            ["combined_arms"] = MainBattleTank,

            ["recon"] = ScoutCar,
            ["armoured_recon"] = ScoutCar,

            // --- aviation ---
            // These are Category=Air, so without an override they would resolve
            // to nothing at all rather than to the stand-in rifleman. The three
            // airframes the strike systems already ship cover the whole branch
            // at map scale — a helicopter reads as a helicopter.
            ["attack_helicopter"] = AttackHelicopter,
            ["recon_helicopter"] = AttackHelicopter,
            ["transport_helicopter"] = AttackHelicopter,
            ["utility_helicopter"] = AttackHelicopter,
            ["medevac_helicopter"] = AttackHelicopter,

            ["cas_aircraft"] = StrikeFighter,
            ["strike_aircraft"] = StrikeFighter,
            ["fighter_aircraft"] = StrikeFighter,
            ["isr_aircraft"] = StrikeFighter,
            ["aewc"] = StrikeFighter,
            // The airlift formation flies the airlifter, now that the game owns
            // one. It was a strike fighter only because there was nothing else
            // with wings — a transport drawn as a fast jet is exactly the kind
            // of stand-in this library exists to retire.
            ["transport_aircraft"] = TransportAircraft,
            ["aerial_refuelling"] = StrikeFighter,
            ["ew_aircraft"] = StrikeFighter,

            // --- unmanned ---
            // Only the quadcopter-shaped ones. A MALE drone or a long-range
            // one-way airframe is not a quad, and showing one would be the same
            // mistake as showing a rifleman for a drone.
            ["fpv_attack_uas"] = KamikazeDrone,
            ["loitering_munition"] = KamikazeDrone,
            ["interceptor_uas"] = KamikazeDrone,
            ["cargo_uas"] = KamikazeDrone,
            ["decoy_uas"] = KamikazeDrone,

            // The fixed-wing unmanned types. A surveillance drone is not a quad
            // and never looked like one; now that the game owns a twin-boom ISR
            // airframe, the types whose job is to loiter and look get it.
            ["recon_uas"] = ReconDrone,
            ["armed_uas"] = ReconDrone,
            ["ew_uas"] = ReconDrone,
            ["relay_uas"] = ReconDrone
        };

        public static UnitModelDef Get(string modelId) =>
            modelId != null && Models.TryGetValue(modelId, out var def) ? def : null;

        /// <summary>
        /// Builds a live instance of a model, whichever kind it is: a procedural
        /// one is constructed, an imported one is instantiated from its prefab.
        /// Returns null — having logged why — when neither is possible.
        ///
        /// Every flight and preview goes through here rather than calling
        /// <c>Resources.Load</c> itself. That was already golden rule 10; it
        /// matters more now that a model can legitimately have no prefab at all,
        /// because a call site checking for one would decide the kamikaze drone
        /// was missing when it is the one model that cannot be.
        /// </summary>
        public static GameObject CreateInstance(string modelId, Transform parent)
        {
            var def = Get(modelId);
            if (def == null)
            {
                Debug.LogError($"[UnitModelLibrary] No model '{modelId}'.");
                return null;
            }
            return CreateInstance(def, parent);
        }

        public static GameObject CreateInstance(UnitModelDef def, Transform parent)
        {
            if (def == null) return null;

            if (def.IsProcedural)
            {
                var built = ProceduralModels.Build(def.proceduralId);
                if (built == null)
                {
                    Debug.LogError($"[UnitModelLibrary] ProceduralModels cannot build '{def.proceduralId}'.");
                    return null;
                }
                built.transform.SetParent(parent, false);
                return built;
            }

            if (string.IsNullOrEmpty(def.resourcePath)) return null;

            var prefab = Resources.Load<GameObject>(def.resourcePath);
            if (prefab == null)
            {
                Debug.LogWarning($"[UnitModelLibrary] Model '{def.resourcePath}' is not installed. " +
                    "Run Tools > Iron Meridian > Install Unit Models (docs/09-3D-MODELS.md).");
                return null;
            }

            return Object.Instantiate(prefab, parent);
        }

        /// <summary>The model that represents this unit type, or null when none exists yet.</summary>
        public static UnitModelDef Resolve(UnitDefinition unit)
        {
            if (unit == null) return null;
            if (Overrides.TryGetValue(unit.id, out string id)) return Get(id);
            return Get(DefaultFor(unit));
        }

        /// <summary>
        /// Fallback assignment for the unit types with no equipment of their own
        /// imported yet: a soldier stands in for any ground formation. Anything
        /// that is not on the ground — drones, aircraft, ships — gets nothing
        /// rather than a misleading infantryman.
        /// </summary>
        static string DefaultFor(UnitDefinition unit) =>
            unit.Category == UnitCategory.CoreGround ? SoldierRifleman : null;

        /// <summary>Every model in the library — used by the installer and the docs check.</summary>
        public static IEnumerable<UnitModelDef> All => Models.Values;

        /// <summary>Model id → definition, for the installer's log messages.</summary>
        public static IEnumerable<KeyValuePair<string, UnitModelDef>> Entries => Models;
    }
}
