using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Data;

namespace IronMeridian.Models
{
    /// <summary>
    /// One 3D model entry: where to load it from and how to frame and animate it.
    /// Keep this in step with docs/09-3D-MODELS.md.
    /// </summary>
    public class UnitModelDef
    {
        /// <summary>Resources path of the prefab, generated by Tools > Iron Meridian > Install Unit Models.</summary>
        public string resourcePath;

        /// <summary>Human name of the source asset, for the docs and for log messages.</summary>
        public string sourceAsset;

        /// <summary>
        /// File names the installer will accept for the source mesh, without
        /// extension, in order of preference.
        ///
        /// A list rather than one name because asset packs rename their meshes
        /// between versions and none of these are ours. The installer takes the
        /// first that exists and names the rest in its log when it finds none,
        /// so adapting to a pack's actual naming is a one-line edit here rather
        /// than a hunt through the installer.
        /// </summary>
        public string[] sourceCandidates = System.Array.Empty<string>();

        /// <summary>Legacy clip played when the model is just standing there; null for static props.</summary>
        public string idleClip = ModelClips.CombatIdle;

        /// <summary>
        /// False for vehicles and props, which ship as static meshes. The
        /// installer skips the Legacy-rig conversion for them — forcing a rig
        /// type onto a mesh with no skeleton achieves nothing and reimports the
        /// whole pack for no reason.
        /// </summary>
        public bool animated = true;

        /// <summary>Multiplier applied after automatic bounds framing — nudge only if a model sits oddly.</summary>
        public float framing = 1f;
    }

    /// <summary>Names the game uses for animation states, independent of the clip's file name.</summary>
    public static class ModelClips
    {
        public const string CombatIdle = "combat_idle";
        public const string CombatRun = "combat_run";
        public const string CombatShoot = "combat_shoot";
    }

    /// <summary>
    /// Resolves a unit definition to the 3D model that represents it.
    ///
    /// The rifleman stands in for any ground formation that has nothing more
    /// specific; the entries below override that for the unit types whose own
    /// equipment has been imported. Drones deliberately get nothing rather than
    /// a misleading infantryman.
    ///
    /// A model listed here whose pack is **not imported** resolves normally and
    /// the preview says which prefab is missing and how to build it — rather
    /// than quietly showing a soldier where a Leopard should be. The pack each
    /// entry needs is named in <c>sourceAsset</c> and in docs/09-3D-MODELS.md.
    /// </summary>
    public static class UnitModelLibrary
    {
        public const string SoldierRifleman = "soldier_rifleman";
        public const string AirDefenceRadar = "air_defence_radar";
        public const string FieldArtillery = "field_artillery";
        public const string SurfaceToAirMissile = "sam_launcher";
        public const string MilitaryTruck = "military_truck";
        public const string MainBattleTank = "main_battle_tank";
        public const string ScoutCar = "scout_car";
        public const string StealthBomber = "stealth_bomber";

        static readonly Dictionary<string, UnitModelDef> Models = new Dictionary<string, UnitModelDef>
        {
            [SoldierRifleman] = new UnitModelDef
            {
                resourcePath = "Models/Soldier_Rifleman",
                sourceAsset = "Low Poly Soldiers Demo — Soldier_demo.FBX",
                sourceCandidates = new[] { "Soldier_demo" },
                idleClip = ModelClips.CombatIdle,
                animated = true
            },

            [AirDefenceRadar] = new UnitModelDef
            {
                resourcePath = "Models/AirDefenceRadar",
                sourceAsset = "Anti-Air Defense Radar",
                sourceCandidates = new[]
                {
                    "Anti_Air_Defense_Radar", "AntiAirDefenseRadar", "AntiAirRadar", "Radar"
                },
                idleClip = null,
                animated = false
            },

            [FieldArtillery] = new UnitModelDef
            {
                resourcePath = "Models/FieldArtillery",
                sourceAsset = "Military Prop Pack: Defense",
                sourceCandidates = new[]
                {
                    "Howitzer", "Artillery", "Field_Gun", "Cannon", "AntiTankGun"
                },
                idleClip = null,
                animated = false
            },

            [SurfaceToAirMissile] = new UnitModelDef
            {
                resourcePath = "Models/SamLauncher",
                sourceAsset = "Homing Missile",
                sourceCandidates = new[]
                {
                    "HomingMissile", "Homing_Missile", "Missile", "Rocket"
                },
                idleClip = null,
                animated = false,
                // A missile is long and thin; the bounds fit would otherwise put
                // the camera close enough to crop the fins.
                framing = 1.25f
            },

            [MilitaryTruck] = new UnitModelDef
            {
                resourcePath = "Models/MilitaryTruck",
                sourceAsset = "ZIL-130 Military Truck",
                sourceCandidates = new[]
                {
                    "ZIL-130", "ZIL130", "Zil_130", "ZIL_130", "Zil130"
                },
                idleClip = null,
                animated = false
            },

            [MainBattleTank] = new UnitModelDef
            {
                resourcePath = "Models/Leopard2",
                sourceAsset = "Tank Leopard 2",
                sourceCandidates = new[]
                {
                    "Leopard2", "Leopard_2", "Leopard2A6", "Leopard2A4", "Leopard"
                },
                idleClip = null,
                animated = false
            },

            [ScoutCar] = new UnitModelDef
            {
                resourcePath = "Models/ScoutCar",
                sourceAsset = "M3A1 Scout Car",
                sourceCandidates = new[]
                {
                    "M3A1", "M3A1_Scout_Car", "M3A1ScoutCar", "ScoutCar"
                },
                idleClip = null,
                animated = false
            },

            // Not a unit: this one is flown by AirStrikeSystem rather than
            // deployed, so it has no entry in Overrides below and Resolve()
            // never returns it. It is here because the library is the only
            // sanctioned way to reach a model prefab (golden rule 10), and
            // because the installer builds its prefab from this list.
            [StealthBomber] = new UnitModelDef
            {
                resourcePath = "Models/StealthBomber",
                sourceAsset = "Hessburg — Stealth Bomber (Built-In)",
                sourceCandidates = new[]
                {
                    "Stealth_Bomber", "StealthBomber", "Stealth Bomber", "B2", "B-2"
                },
                idleClip = null,
                // A flying wing with no moving surfaces. Its flight is animated
                // in code by BomberRun, not by a clip.
                animated = false
            }
        };

        /// <summary>
        /// Per-unit-id model assignments. Anything not listed falls back to
        /// <see cref="DefaultFor"/>. One model can serve several unit types —
        /// a truck is a truck whether it is carrying supplies or people.
        /// </summary>
        static readonly Dictionary<string, string> Overrides = new Dictionary<string, string>
        {
            ["ad_radar"] = AirDefenceRadar,
            ["air_defence"] = AirDefenceRadar,

            ["artillery"] = FieldArtillery,
            ["rocket_artillery"] = FieldArtillery,

            ["sam"] = SurfaceToAirMissile,

            ["transport"] = MilitaryTruck,
            ["logistics"] = MilitaryTruck,
            ["supply"] = MilitaryTruck,

            ["armour"] = MainBattleTank,

            ["recon"] = ScoutCar
        };

        public static UnitModelDef Get(string modelId) =>
            modelId != null && Models.TryGetValue(modelId, out var def) ? def : null;

        /// <summary>The model that represents this unit type, or null when none exists yet.</summary>
        public static UnitModelDef Resolve(UnitDefinition unit)
        {
            if (unit == null) return null;
            if (Overrides.TryGetValue(unit.id, out string id)) return Get(id);
            return Get(DefaultFor(unit));
        }

        /// <summary>
        /// Fallback assignment for the unit types with no equipment of their own
        /// imported yet: a soldier stands in for any ground formation. Drones get
        /// nothing rather than a misleading infantryman.
        /// </summary>
        static string DefaultFor(UnitDefinition unit) =>
            unit.Category == UnitCategory.Drone ? null : SoldierRifleman;

        /// <summary>Every model in the library — used by the installer and the docs check.</summary>
        public static IEnumerable<UnitModelDef> All => Models.Values;

        /// <summary>Model id → definition, for the installer's log messages.</summary>
        public static IEnumerable<KeyValuePair<string, UnitModelDef>> Entries => Models;
    }
}
