using System;
using System.Collections.Generic;

namespace IronMeridian.Data
{
    /// <summary>
    /// One deployed unit inside a map save. Positions are geodetic (WGS84),
    /// so saves are independent of the Unity origin.
    /// </summary>
    [Serializable]
    public class UnitState
    {
        public string instanceId;       // unique per placed unit
        public string defId;            // UnitDefinition.id
        public string team;             // "User" | "Enemy"
        public string affiliation;      // Friendly | Hostile | Neutral | Unknown
        public string echelon;          // Echelon name
        public string customName;       // e.g. "2nd Battalion, 4th Infantry"
        public string groupId;          // shared id for units grouped together, "" if none
        public string groupName;        // player-chosen group name, "" if none

        public double latitude;
        public double longitude;
        public double heightMeters;
        public float headingDeg;

        public float strength;          // 0..1 remaining strength
        public float organisation;      // 0..100 current
        public float morale;            // 0..100 current
        public string status;           // UnitStatus name

        // Current sustainment state (starts from definition stocks)
        public int ammo;
        public float fuel;
        public int foodDays;

        /// <summary>
        /// Deep copy. UnitState is a reference type shared with the live actor,
        /// so clipboard and undo snapshots must copy it or they would track the
        /// unit's later edits instead of recording its state at the time.
        /// </summary>
        public UnitState Clone() => new UnitState
        {
            instanceId = instanceId,
            defId = defId,
            team = team,
            affiliation = affiliation,
            echelon = echelon,
            customName = customName,
            groupId = groupId,
            groupName = groupName,
            latitude = latitude,
            longitude = longitude,
            heightMeters = heightMeters,
            headingDeg = headingDeg,
            strength = strength,
            organisation = organisation,
            morale = morale,
            status = status,
            ammo = ammo,
            fuel = fuel,
            foodDays = foodDays
        };

        public Team TeamEnum => team == "Enemy" ? Team.Enemy : Team.User;
        public Affiliation AffiliationEnum =>
            Enum.TryParse<Affiliation>(affiliation, out var a) ? a : Affiliation.Unknown;
        public Echelon EchelonEnum =>
            Enum.TryParse<Echelon>(echelon, out var e) ? e : Echelon.Company;
    }

    [Serializable]
    public class GeoPoint
    {
        public double latitude;
        public double longitude;
        public double heightMeters;
    }

    /// <summary>
    /// A tactical control measure drawn on the map — boundary, FEBA, phase
    /// line. Modelled on MIL-STD-2525 N-point tactical graphics (an ordered
    /// vertex list plus amplifiers), so these could be exported to KML/CoT
    /// later without reshaping the data.
    ///
    /// Fields added after the original schema default harmlessly on old saves:
    /// JsonUtility leaves missing fields at their initialiser values.
    /// </summary>
    [Serializable]
    public class MapLineData
    {
        public string id;
        public string kind;             // LineKind name
        public string team;             // owning side ("" when it separates both)
        public bool is3D;               // rendered clamped to terrain (3D) or flat (2D)
        public bool autoGenerated;      // true = maintained by a system, regenerated on demand
        public List<GeoPoint> points = new List<GeoPoint>();

        // ---- amplifiers (APP-6A / FM 101-5-1 labelling) ----

        /// <summary>Caption drawn on the line, e.g. "FEBA" or "PL BLUE".</summary>
        public string label = "";
        /// <summary>Echelon size marking straddling a boundary, e.g. "II", "X".</summary>
        public string echelon = "";
        /// <summary>Designation of the formation on each side of a boundary.</summary>
        public string leftLabel = "";
        public string rightLabel = "";
        /// <summary>Planned / on-order control measures are drawn broken, actual ones solid.</summary>
        public bool planned;
    }

    /// <summary>
    /// A complete scenario/map save. Serialized to JSON, one file per map, in
    /// persistentDataPath/Maps (user saves) or StreamingAssets/Maps (shipped defaults).
    /// </summary>
    [Serializable]
    public class MapSaveData
    {
        public string mapName = "New Map";
        public string savedAtUtc;

        // Camera / view
        public double centerLatitude;
        public double centerLongitude;
        public double cameraHeightMeters = 12000;
        public string viewMode = "Mode3D"; // Mode2D | Mode3D
        public string mapStyle = "Satellite"; // Satellite | Terrain | Roads

        public List<UnitState> units = new List<UnitState>();
        public List<MapLineData> lines = new List<MapLineData>();
    }
}
