using System;
using System.Collections.Generic;

namespace IronMeridian.Data
{
    /// <summary>
    /// One deployed unit inside a map save. Positions are geodetic (WGS84),
    /// so saves are independent of the Unity origin.
    /// </summary>
    [Serializable]
    public class UnitState
    {
        public string instanceId;       // unique per placed unit
        public string defId;            // UnitDefinition.id
        public string team;             // "User" | "Enemy"
        public string affiliation;      // Friendly | Hostile | Neutral | Unknown
        public string echelon;          // Echelon name
        public string customName;       // e.g. "2nd Battalion, 4th Infantry"

        public double latitude;
        public double longitude;
        public double heightMeters;
        public float headingDeg;

        public float strength;          // 0..1 remaining strength
        public float organisation;      // 0..100 current
        public float morale;            // 0..100 current
        public string status;           // UnitStatus name

        // Current sustainment state (starts from definition stocks)
        public int ammo;
        public float fuel;
        public int foodDays;

        public Team TeamEnum => team == "Enemy" ? Team.Enemy : Team.User;
        public Affiliation AffiliationEnum =>
            Enum.TryParse<Affiliation>(affiliation, out var a) ? a : Affiliation.Unknown;
        public Echelon EchelonEnum =>
            Enum.TryParse<Echelon>(echelon, out var e) ? e : Echelon.Company;
    }

    [Serializable]
    public class GeoPoint
    {
        public double latitude;
        public double longitude;
        public double heightMeters;
    }

    /// <summary>A drawn polyline on the map: sector boundary or defensive line.</summary>
    [Serializable]
    public class MapLineData
    {
        public string id;
        public string kind;             // "Boundary" | "DefensiveLine"
        public string team;             // owner team for defensive lines ("" for boundaries)
        public bool is3D;               // rendered clamped to terrain (3D) or flat (2D)
        public bool autoGenerated;      // true for the auto-updated front line
        public List<GeoPoint> points = new List<GeoPoint>();
    }

    /// <summary>
    /// A complete scenario/map save. Serialized to JSON, one file per map, in
    /// persistentDataPath/Maps (user saves) or StreamingAssets/Maps (shipped defaults).
    /// </summary>
    [Serializable]
    public class MapSaveData
    {
        public string mapName = "New Map";
        public string savedAtUtc;

        // Camera / view
        public double centerLatitude;
        public double centerLongitude;
        public double cameraHeightMeters = 12000;
        public string viewMode = "Mode3D"; // Mode2D | Mode3D

        public List<UnitState> units = new List<UnitState>();
        public List<MapLineData> lines = new List<MapLineData>();
    }
}
