using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Data;
using IronMeridian.Map;
using IronMeridian.Units;

namespace IronMeridian.Lines
{
    /// <summary>
    /// The three defensive tasks a selected unit can be given from the battle
    /// order bar (FM 3-90 ch.8 — defensive tasks vs security tasks):
    ///
    ///  • **Defend** — prepare a position and fight from it. Lays a defence line
    ///    across the threat axis, a battle position enclosing the ground behind
    ///    it, and pushes the commander's subordinates out along the frontage so
    ///    the line is actually manned instead of merely drawn.
    ///  • **Hold** — retain this ground. Pins the unit where it stands, facing
    ///    the threat, and marks the position.
    ///  • **Guard** — screen the protected force forward of it. Pushes the unit
    ///    out toward the threat, within supporting distance, and marks that
    ///    position.
    ///
    /// Every graphic this produces is ordinary map data: lines go through
    /// <see cref="LineManager"/> and markers through <see cref="MarkerManager"/>,
    /// so a defence survives a save/load like anything else on the map. Ids are
    /// prefixed <c>defence-</c>, keeping them clear of the <c>sector-</c> set
    /// that "clear tactical graphics" regenerates.
    ///
    /// Orientation always comes from the enemy: the threat axis is the bearing
    /// to the centre of the opposing force. With no enemy on the map the unit's
    /// own facing stands in, so the tasks still work while a scenario is being
    /// built up.
    /// </summary>
    public class DefenceOrderSystem : MonoBehaviour
    {
        /// <summary>Vertices along a defence line — enough to bow it without reading as a polygon.</summary>
        const int LinePoints = 9;
        /// <summary>Forward bow at the centre of the line, as a fraction of its frontage.</summary>
        const double BowFraction = 0.10;
        /// <summary>How far ahead of the commander the line is laid, as a fraction of frontage.</summary>
        const double StandoffFraction = 0.35;
        /// <summary>Depth of the battle position behind the line, as a fraction of frontage.</summary>
        const double DepthFraction = 0.45;
        /// <summary>Frontage floor and ceiling, km.</summary>
        const double MinFrontageKm = 1.5, MaxFrontageKm = 45.0;
        /// <summary>Radius searched for subordinates when a unit is not in a named group, km.</summary>
        const double SubordinateSearchKm = 12.0;
        /// <summary>Most subordinates one defence will try to place.</summary>
        const int MaxSubordinates = 12;
        /// <summary>Guard standoff floor and ceiling, km.</summary>
        const double MinGuardKm = 0.6, MaxGuardKm = 8.0;

        public System.Action<string> Flash;

        LineManager _lines;
        MarkerManager _markers;

        public void Init(LineManager lines, MarkerManager markers)
        {
            _lines = lines; _markers = markers;
        }

        // ------------------------------------------------------- Defend

        /// <summary>
        /// Prepares a defence around the selected unit: the line, the battle
        /// position behind it, and the subordinates that man it. Returns false
        /// when there is nothing to defend with.
        /// </summary>
        public bool Defend(UnitActor commander)
        {
            if (commander == null || !commander.IsAlive)
            {
                Flash?.Invoke("Select a unit before ordering a defence.");
                return false;
            }

            var subordinates = Subordinates(commander);
            float threat = ThreatBearing(commander);
            var team = commander.State.TeamEnum;
            double frontageKm = FrontageKm(commander, subordinates.Count);
            double standoffKm = frontageKm * StandoffFraction;
            double depthKm = frontageKm * DepthFraction;

            // Centre of the position: forward of the commander, on the threat axis.
            GeoUtils.Destination(commander.State.latitude, commander.State.longitude,
                threat, standoffKm, out double centreLat, out double centreLon);

            ClearFor(commander);

            var forwardEdge = ArcPoints(centreLat, centreLon, threat, frontageKm,
                frontageKm * BowFraction, LinePoints);

            string designation = Designation(commander);
            _lines.Upsert(new MapLineData
            {
                id = LineId(commander),
                kind = LineKind.DefensiveLine.ToString(),
                team = team.ToString(),
                is3D = true,
                autoGenerated = true,
                points = forwardEdge,
                label = $"DEFENCE LINE — {designation.ToUpperInvariant()}",
                echelon = EchelonInfo.Indicator(commander.State.EchelonEnum)
            });

            _lines.Upsert(new MapLineData
            {
                id = AreaId(commander),
                kind = LineKind.BattlePosition.ToString(),
                team = team.ToString(),
                is3D = true,
                autoGenerated = true,
                points = AreaPoints(centreLat, centreLon, threat, frontageKm, depthKm, forwardEdge)
            });

            _markers.Set(new MapMarkerData
            {
                id = MarkerId(commander),
                kind = MarkerKind.Defend.ToString(),
                team = team.ToString(),
                unitId = commander.State.instanceId,
                label = $"DEFEND\n{designation}",
                latitude = centreLat,
                longitude = centreLon,
                headingDeg = threat
            });

            int placed = DistributeAlongLine(subordinates, centreLat, centreLon, threat, frontageKm);

            // The commander sits back inside the position rather than on the
            // line — it is directing the defence, not holding a slice of it.
            // With nobody to direct it takes the centre of its own line.
            if (subordinates.Count > 0)
            {
                GeoUtils.Destination(centreLat, centreLon, Reciprocal(threat), depthKm * 0.6,
                    out double cpLat, out double cpLon);
                Reposition(commander, cpLat, cpLon, threat);
            }
            else
            {
                commander.SetHeading(threat);
            }

            Flash?.Invoke(placed > 0
                ? $"{designation} defends — {frontageKm:0.#} km frontage, {placed} subordinate unit(s) distributed."
                : $"{designation} defends — {frontageKm:0.#} km frontage (no subordinates to distribute).");
            return true;
        }

        // ------------------------------------------------------- Hold / Guard

        /// <summary>Pins the unit on the ground it is standing on and marks the position.</summary>
        public bool Hold(UnitActor unit)
        {
            if (!Ready(unit, "hold")) return false;

            float threat = ThreatBearing(unit);
            unit.Mover.Cancel();
            unit.SetHeading(threat);
            unit.State.status = UnitStatus.Idle.ToString();

            PinTask(unit, MarkerKind.Hold, "HOLD", unit.State.latitude, unit.State.longitude, threat);
            Flash?.Invoke($"{Designation(unit)} holds its position, oriented {threat:000}°.");
            return true;
        }

        /// <summary>
        /// Pushes the unit forward onto a guard position between the force it is
        /// protecting and the threat, and marks it.
        /// </summary>
        public bool Guard(UnitActor unit)
        {
            if (!Ready(unit, "guard")) return false;

            float threat = ThreatBearing(unit);
            double standoffKm = GuardStandoffKm(unit);
            GeoUtils.Destination(unit.State.latitude, unit.State.longitude, threat, standoffKm,
                out double lat, out double lon);

            PinTask(unit, MarkerKind.Guard, "GUARD", lat, lon, threat);
            Reposition(unit, lat, lon, threat);

            Flash?.Invoke($"{Designation(unit)} guards {standoffKm:0.#} km forward, oriented {threat:000}°.");
            return true;
        }

        bool Ready(UnitActor unit, string task)
        {
            if (unit != null && unit.IsAlive) return true;
            Flash?.Invoke($"Select a unit before ordering it to {task}.");
            return false;
        }

        void PinTask(UnitActor unit, MarkerKind kind, string caption,
            double lat, double lon, float heading)
        {
            _lines.RemoveAutoGenerated($"defence-{unit.State.instanceId}-");
            _markers.Set(new MapMarkerData
            {
                id = $"defence-{unit.State.instanceId}-{kind.ToString().ToLowerInvariant()}",
                kind = kind.ToString(),
                team = unit.State.TeamEnum.ToString(),
                unitId = unit.State.instanceId,
                label = $"{caption}\n{Designation(unit)}",
                latitude = lat,
                longitude = lon,
                headingDeg = heading
            });
        }

        /// <summary>Drops every graphic a previous defensive task left for this unit.</summary>
        public void ClearFor(UnitActor unit)
        {
            if (unit == null) return;
            _lines.RemoveAutoGenerated($"defence-{unit.State.instanceId}-");
            _markers.RemoveForUnit(unit.State.instanceId);
        }

        // ------------------------------------------------------- geometry

        /// <summary>
        /// Points along an arc perpendicular to <paramref name="axisDeg"/>,
        /// bowed forward at the centre. A straight line across a frontage reads
        /// as a boundary; a defence line curves toward what it faces.
        /// </summary>
        static List<GeoPoint> ArcPoints(double centreLat, double centreLon, float axisDeg,
            double frontageKm, double bowKm, int count)
        {
            double lateral = axisDeg + 90.0;
            var pts = new List<GeoPoint>(count);
            for (int i = 0; i < count; i++)
            {
                double t = count == 1 ? 0.0 : i / (double)(count - 1) - 0.5;   // -0.5 .. +0.5
                GeoUtils.Destination(centreLat, centreLon, lateral, t * frontageKm,
                    out double lat, out double lon);

                // Parabolic bow: full at the centre, nothing at the flanks.
                double bow = bowKm * (1.0 - 4.0 * t * t);
                if (System.Math.Abs(bow) > 1e-6)
                    GeoUtils.Destination(lat, lon, axisDeg, bow, out lat, out lon);

                pts.Add(new GeoPoint { latitude = lat, longitude = lon });
            }
            return pts;
        }

        /// <summary>
        /// Closed battle position: the defence line's own trace forward, a rear
        /// edge <paramref name="depthKm"/> behind it, and back to the start so
        /// the polygon closes.
        /// </summary>
        static List<GeoPoint> AreaPoints(double centreLat, double centreLon, float axisDeg,
            double frontageKm, double depthKm, List<GeoPoint> line)
        {
            var pts = new List<GeoPoint>(line.Count * 2 + 1);
            pts.AddRange(line);

            GeoUtils.Destination(centreLat, centreLon, axisDeg + 180.0, depthKm,
                out double rearLat, out double rearLon);
            var rear = ArcPoints(rearLat, rearLon, axisDeg, frontageKm * 0.92, -depthKm * 0.18, LinePoints);
            for (int i = rear.Count - 1; i >= 0; i--) pts.Add(rear[i]);

            pts.Add(new GeoPoint { latitude = pts[0].latitude, longitude = pts[0].longitude });
            return pts;
        }

        /// <summary>
        /// Spreads subordinates evenly across the frontage and marches each to
        /// its slot facing the threat. Assignment is by current lateral position,
        /// so units take the slot nearest them and columns do not cross.
        /// </summary>
        int DistributeAlongLine(List<UnitActor> units, double centreLat, double centreLon,
            float axisDeg, double frontageKm)
        {
            if (units.Count == 0) return 0;

            double lateralBearing = axisDeg + 90.0;
            units.Sort((a, b) => LateralOffsetKm(a, centreLat, centreLon, lateralBearing)
                .CompareTo(LateralOffsetKm(b, centreLat, centreLon, lateralBearing)));

            int placed = 0;
            for (int i = 0; i < units.Count; i++)
            {
                // Slot centres, so the flanks keep half a sub-sector of room.
                double t = (i + 0.5) / units.Count - 0.5;
                GeoUtils.Destination(centreLat, centreLon, lateralBearing, t * frontageKm,
                    out double lat, out double lon);

                if (Reposition(units[i], lat, lon, axisDeg)) placed++;
            }
            return placed;
        }

        /// <summary>
        /// Sends a unit to a point. In battle that is a routed march that leaves
        /// a trail; the same call outside battle would be a silent no-op, so the
        /// unit is placed directly instead — a defence laid out while planning
        /// should still lay itself out.
        /// </summary>
        static bool Reposition(UnitActor unit, double lat, double lon, float faceDeg)
        {
            if (unit == null || !unit.IsAlive) return false;
            if (unit.Mover.MoveTo(lat, lon, faceDeg)) return true;

            unit.SetPosition(lat, lon);
            unit.SetHeading(faceDeg);
            return true;
        }

        static double LateralOffsetKm(UnitActor u, double centreLat, double centreLon, double lateralBearing)
        {
            GeoUtils.ToLocalKm(centreLat, centreLon, u.State.latitude, u.State.longitude,
                out double east, out double north);
            double rad = lateralBearing * System.Math.PI / 180.0;
            // Bearings run clockwise from north, so the unit vector is (sin, cos).
            return east * System.Math.Sin(rad) + north * System.Math.Cos(rad);
        }

        // ------------------------------------------------------- inputs

        /// <summary>
        /// Bearing to the centre of the opposing force — what the defence is
        /// oriented on. Falls back to the unit's own facing when the other side
        /// has nothing on the map yet.
        /// </summary>
        public static float ThreatBearing(UnitActor unit)
        {
            var enemy = unit.State.TeamEnum == Team.User ? Team.Enemy : Team.User;
            double lat = 0, lon = 0;
            int n = 0;
            foreach (var e in UnitRegistry.OfTeam(enemy))
            {
                if (e == null || !e.IsAlive) continue;
                lat += e.State.latitude; lon += e.State.longitude; n++;
            }
            if (n == 0) return unit.State.headingDeg;
            return GeoUtils.BearingDeg(unit.State.latitude, unit.State.longitude, lat / n, lon / n);
        }

        /// <summary>
        /// The units this one commands: its group if it has one, otherwise the
        /// smaller friendly formations standing near it. Grouping is explicit in
        /// the editor, so it wins; proximity is the fallback that makes the order
        /// useful on a map nobody has grouped.
        /// </summary>
        static List<UnitActor> Subordinates(UnitActor commander)
        {
            var result = new List<UnitActor>();
            string group = commander.State.groupId;

            if (!string.IsNullOrEmpty(group))
            {
                foreach (var u in UnitRegistry.OfTeam(commander.State.TeamEnum))
                    if (u != null && u != commander && u.IsAlive && u.State.groupId == group)
                        result.Add(u);
                if (result.Count > 0) return Trim(result);
            }

            foreach (var u in UnitRegistry.OfTeam(commander.State.TeamEnum))
            {
                if (u == null || u == commander || !u.IsAlive) continue;
                if (u.State.EchelonEnum >= commander.State.EchelonEnum) continue;
                if (!string.IsNullOrEmpty(u.State.groupId) && u.State.groupId != group) continue;
                if (GeoUtils.DistanceKm(commander.State.latitude, commander.State.longitude,
                        u.State.latitude, u.State.longitude) > SubordinateSearchKm) continue;
                result.Add(u);
            }
            return Trim(result);
        }

        static List<UnitActor> Trim(List<UnitActor> units)
        {
            if (units.Count > MaxSubordinates) units.RemoveRange(MaxSubordinates, units.Count - MaxSubordinates);
            return units;
        }

        /// <summary>
        /// Frontage a formation defends. Scaled off echelon bulk rather than a
        /// per-echelon table so it stays sensible for any unit type, and widened
        /// a little for each subordinate that has to fit on the line.
        /// </summary>
        static double FrontageKm(UnitActor commander, int subordinates)
        {
            double bulk = Mathf.Max(1f, EchelonInfo.ManpowerMultiplier(commander.State.EchelonEnum));
            double km = 1.1 * System.Math.Sqrt(bulk) * System.Math.Sqrt(System.Math.Max(2, subordinates + 1));
            return System.Math.Min(MaxFrontageKm, System.Math.Max(MinFrontageKm, km));
        }

        /// <summary>How far forward a guard force operates — within supporting range of its parent.</summary>
        static double GuardStandoffKm(UnitActor unit)
        {
            double bulk = Mathf.Max(1f, EchelonInfo.ManpowerMultiplier(unit.State.EchelonEnum));
            double km = 0.7 * System.Math.Sqrt(bulk);
            return System.Math.Min(MaxGuardKm, System.Math.Max(MinGuardKm, km));
        }

        static float Reciprocal(float bearing) => (bearing + 180f) % 360f;

        static string LineId(UnitActor u) => $"defence-{u.State.instanceId}-line";
        static string AreaId(UnitActor u) => $"defence-{u.State.instanceId}-area";
        static string MarkerId(UnitActor u) => $"defence-{u.State.instanceId}-defend";

        static string Designation(UnitActor u) =>
            string.IsNullOrEmpty(u.State.customName) ? u.Def.name : u.State.customName;
    }
}
