using System.Collections.Generic;
using UnityEngine;
using IronMeridian.Core;
using IronMeridian.Data;
using IronMeridian.Units;

namespace IronMeridian.Lines
{
    /// <summary>
    /// Automatically maintains the boundary line between the two teams.
    /// As units move or are destroyed, the front line shifts: for each band
    /// across the front, the boundary point is the power-weighted midpoint
    /// between the closest blue and red units — a stronger side pushes the
    /// line towards the weaker one.
    /// </summary>
    public class FrontlineSystem : MonoBehaviour
    {
        public bool AutoUpdate = true;
        const int Samples = 9;

        LineManager _lines;
        float _timer;

        public void Init(LineManager lines)
        {
            _lines = lines;
            UnitRegistry.Changed += OnUnitsChanged;
        }

        void OnDestroy() => UnitRegistry.Changed -= OnUnitsChanged;

        void OnUnitsChanged() => _timer = GameConfig.FrontlineUpdateSeconds; // recompute soon

        void Update()
        {
            if (!AutoUpdate) return;
            _timer += Time.deltaTime;
            if (_timer < GameConfig.FrontlineUpdateSeconds) return;
            _timer = 0f;
            Recompute();
        }

        public void Recompute()
        {
            var blues = new List<UnitActor>(UnitRegistry.OfTeam(Team.User));
            var reds = new List<UnitActor>(UnitRegistry.OfTeam(Team.Enemy));
            if (blues.Count == 0 || reds.Count == 0) return;

            // Centroids define the front axis
            double bLat = 0, bLon = 0, rLat = 0, rLon = 0;
            foreach (var u in blues) { bLat += u.State.latitude; bLon += u.State.longitude; }
            foreach (var u in reds) { rLat += u.State.latitude; rLon += u.State.longitude; }
            bLat /= blues.Count; bLon /= blues.Count;
            rLat /= reds.Count; rLon /= reds.Count;

            // Front direction (blue->red) and its perpendicular (along the front)
            double dLat = rLat - bLat, dLon = rLon - bLon;
            double len = System.Math.Sqrt(dLat * dLat + dLon * dLon);
            if (len < 1e-7) return;
            double pLat = -dLon / len, pLon = dLat / len;   // perpendicular unit vector

            double midLat = (bLat + rLat) / 2, midLon = (bLon + rLon) / 2;
            double halfSpan = System.Math.Max(len * 1.2, 0.05);

            var pts = new List<GeoPoint>();
            for (int i = 0; i < Samples; i++)
            {
                double f = (i / (double)(Samples - 1) - 0.5) * 2;   // -1..1 along the front
                double sLat = midLat + pLat * halfSpan * f;
                double sLon = midLon + pLon * halfSpan * f;

                // Nearest unit of each side to this band
                var nb = Nearest(blues, sLat, sLon, out double nbDist);
                var nr = Nearest(reds, sLat, sLon, out double nrDist);
                if (nb == null || nr == null) continue;

                // Power-weighted midpoint: stronger side pushes the line
                float bp = nb.CurrentPower(), rp = nr.CurrentPower();
                double w = bp + rp > 0 ? bp / (bp + rp) : 0.5;   // 0..1, high = blue stronger
                double lat = nb.State.latitude + (nr.State.latitude - nb.State.latitude) * w;
                double lon = nb.State.longitude + (nr.State.longitude - nb.State.longitude) * w;

                pts.Add(new GeoPoint { latitude = lat, longitude = lon });
            }
            if (pts.Count < 2) return;

            var boundary = _lines.FindAutoBoundary();
            if (boundary == null)
            {
                boundary = _lines.Add(new MapLineData
                {
                    id = "boundary-auto",
                    kind = LineKind.Boundary.ToString(),
                    team = "",
                    is3D = true,
                    autoGenerated = true,
                    points = pts
                });
            }
            else boundary.SetPoints(pts);
        }

        static UnitActor Nearest(List<UnitActor> units, double lat, double lon, out double best)
        {
            UnitActor result = null; best = double.MaxValue;
            foreach (var u in units)
            {
                double d = (u.State.latitude - lat) * (u.State.latitude - lat) +
                           (u.State.longitude - lon) * (u.State.longitude - lon);
                if (d < best) { best = d; result = u; }
            }
            return result;
        }
    }
}
