using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using IronMeridian.Data;
using IronMeridian.Map;

namespace IronMeridian.Lines
{
    /// <summary>
    /// Click-to-draw tool for sector boundaries and defensive lines.
    ///   Left click  — add a point on the terrain
    ///   Right click / Enter — finish the line (min 2 points)
    ///   Esc         — cancel
    /// Lines can be drawn as 2D (flat) or 3D (terrain-following).
    /// </summary>
    public class LineDrawTool : MonoBehaviour
    {
        public enum Mode { None, Boundary, DefensiveLine }

        public Mode Current { get; private set; } = Mode.None;
        public bool Draw3D = true;
        public Team DefensiveTeam = Team.User;

        public event System.Action<Mode> ModeChanged;

        MapManager _map;
        Camera _cam;
        LineManager _lineManager;
        readonly List<GeoPoint> _points = new List<GeoPoint>();
        MapLine _preview;
        int _counter;

        public void Init(MapManager map, Camera cam, LineManager lines)
        {
            _map = map; _cam = cam; _lineManager = lines;
        }

        public void StartDrawing(Mode mode)
        {
            CancelDrawing();
            Current = mode;
            ModeChanged?.Invoke(Current);
        }

        public void CancelDrawing()
        {
            if (_preview != null) _lineManager.Remove(_preview);
            _preview = null;
            _points.Clear();
            Current = Mode.None;
            ModeChanged?.Invoke(Current);
        }

        void Update()
        {
            if (Current == Mode.None || _cam == null) return;
            if (EventSystem.current != null && EventSystem.current.IsPointerOverGameObject()) return;

            if (Input.GetMouseButtonDown(0) &&
                _map.RaycastGround(_cam, Input.mousePosition, out Vector3 world))
            {
                GeoUtils.UnityToGeo(_map.Georeference, world, out double lat, out double lon, out double h);
                _points.Add(new GeoPoint { latitude = lat, longitude = lon, heightMeters = h });
                UpdatePreview();
            }

            if (Input.GetMouseButtonDown(1) || Input.GetKeyDown(KeyCode.Return))
                FinishLine();

            if (Input.GetKeyDown(KeyCode.Escape))
                CancelDrawing();
        }

        void UpdatePreview()
        {
            if (_preview == null && _points.Count >= 1)
            {
                _preview = _lineManager.Add(NewData());
            }
            if (_preview != null)
                _preview.SetPoints(new List<GeoPoint>(_points));
        }

        void FinishLine()
        {
            if (_points.Count < 2)
            {
                CancelDrawing();
                return;
            }
            if (_preview == null) _preview = _lineManager.Add(NewData());
            _preview.SetPoints(new List<GeoPoint>(_points));
            _preview = null;
            _points.Clear();
            Current = Mode.None;
            ModeChanged?.Invoke(Current);
        }

        MapLineData NewData() => new MapLineData
        {
            id = $"{(Current == Mode.Boundary ? "boundary" : "defline")}-{++_counter}-{Random.Range(1000, 9999)}",
            kind = Current == Mode.Boundary ? LineKind.Boundary.ToString() : LineKind.DefensiveLine.ToString(),
            team = Current == Mode.DefensiveLine ? DefensiveTeam.ToString() : "",
            is3D = Draw3D,
            autoGenerated = false,
            points = new List<GeoPoint>()
        };
    }
}
