using System.Collections.Generic;
using UnityEngine;
using CesiumForUnity;
using IronMeridian.Data;

namespace IronMeridian.Lines
{
    /// <summary>Owns every drawn line on the map; syncs with save data.</summary>
    public class LineManager : MonoBehaviour
    {
        readonly List<MapLine> _lines = new List<MapLine>();
        CesiumGeoreference _geo;

        public IReadOnlyList<MapLine> Lines => _lines;

        public void Init(CesiumGeoreference geo) => _geo = geo;

        public MapLine Add(MapLineData data)
        {
            var line = MapLine.Create(_geo, data);
            _lines.Add(line);
            return line;
        }

        public void Remove(MapLine line)
        {
            _lines.Remove(line);
            if (line != null) Destroy(line.gameObject);
        }

        // There is no FindAutoBoundary any more. It searched by kind and by the
        // auto-generated flag for what was always exactly one line;
        // FrontlineSystem now owns that line's id and asks for it by name, which
        // cannot pick up somebody else's boundary by accident.

        public MapLine Find(string id)
        {
            foreach (var l in _lines)
                if (l != null && l.Data.id == id) return l;
            return null;
        }

        /// <summary>
        /// Replace-or-create by id. Regenerating tactical graphics reuses the
        /// existing line objects so the LineRenderers (and their materials) are
        /// not churned every recompute.
        /// </summary>
        public MapLine Upsert(MapLineData data)
        {
            var existing = Find(data.id);
            if (existing == null) return Add(data);
            existing.SetPoints(data.points);
            return existing;
        }

        /// <summary>Drops every auto-generated line whose id starts with the given prefix.</summary>
        public int RemoveAutoGenerated(string idPrefix)
        {
            int removed = 0;
            for (int i = _lines.Count - 1; i >= 0; i--)
            {
                var l = _lines[i];
                if (l == null || !l.Data.autoGenerated) continue;
                if (!string.IsNullOrEmpty(idPrefix) && !l.Data.id.StartsWith(idPrefix)) continue;
                _lines.RemoveAt(i);
                Destroy(l.gameObject);
                removed++;
            }
            return removed;
        }

        public void RebuildAll()
        {
            foreach (var l in _lines) l.Rebuild();
        }

        public void SetAll3D(bool is3D)
        {
            foreach (var l in _lines) l.Set3D(is3D);
        }

        public List<MapLineData> Serialize()
        {
            var result = new List<MapLineData>();
            foreach (var l in _lines) result.Add(l.Data);
            return result;
        }

        public void LoadFrom(List<MapLineData> data)
        {
            foreach (var l in _lines) if (l != null) Destroy(l.gameObject);
            _lines.Clear();
            foreach (var d in data) Add(d);
        }
    }
}
