using System.Collections.Generic;
using UnityEngine;
using CesiumForUnity;
using IronMeridian.Data;

namespace IronMeridian.Lines
{
    /// <summary>Owns every drawn line on the map; syncs with save data.</summary>
    public class LineManager : MonoBehaviour
    {
        readonly List<MapLine> _lines = new List<MapLine>();
        CesiumGeoreference _geo;

        public IReadOnlyList<MapLine> Lines => _lines;

        public void Init(CesiumGeoreference geo) => _geo = geo;

        public MapLine Add(MapLineData data)
        {
            var line = MapLine.Create(_geo, data);
            _lines.Add(line);
            return line;
        }

        public void Remove(MapLine line)
        {
            _lines.Remove(line);
            if (line != null) Destroy(line.gameObject);
        }

        public MapLine FindAutoBoundary()
        {
            foreach (var l in _lines)
                if (l.Data.autoGenerated && l.Data.kind == LineKind.Boundary.ToString())
                    return l;
            return null;
        }

        public void RebuildAll()
        {
            foreach (var l in _lines) l.Rebuild();
        }

        public void SetAll3D(bool is3D)
        {
            foreach (var l in _lines) l.Set3D(is3D);
        }

        public List<MapLineData> Serialize()
        {
            var result = new List<MapLineData>();
            foreach (var l in _lines) result.Add(l.Data);
            return result;
        }

        public void LoadFrom(List<MapLineData> data)
        {
            foreach (var l in _lines) if (l != null) Destroy(l.gameObject);
            _lines.Clear();
            foreach (var d in data) Add(d);
        }
    }
}
