using System.Collections.Generic;
using UnityEngine;
using CesiumForUnity;
using IronMeridian.Core;
using IronMeridian.Data;
using IronMeridian.Map;
using IronMeridian.Units;

namespace IronMeridian.Lines
{
    /// <summary>
    /// Derives a side's tactical control measures from where its units actually
    /// stand: lateral sector boundaries between adjacent formations, the FEBA
    /// through the forward ones, and a rear boundary behind them.
    ///
    /// Doctrine this follows (APP-6A, FM 101-5-1, FM 3-90):
    ///  • A lateral boundary is the left/right limit of a formation's area of
    ///    operations. It runs REAR TO FRONT — roughly perpendicular to the
    ///    front — and is extended beyond the FLOT by a forward boundary, so it
    ///    is drawn past the foremost units rather than stopping at them.
    ///  • The FEBA is the foremost limit of the areas where ground combat units
    ///    are deployed, EXCLUDING screening/covering forces. It is the line
    ///    that connects the forward defending units. (MLR is the legacy term
    ///    for roughly this; it has no APP-6A graphic, so it is not used here.)
    ///  • A rear boundary runs parallel to the front; ground behind it belongs
    ///    to the higher commander.
    ///  • Actual control measures are solid, planned ones broken.
    ///
    /// Why not a Voronoi partition, which is the obvious first instinct: a raw
    /// Voronoi diagram builds a cell around EVERY unit, including units echeloned
    /// in depth, so it emits cell walls running laterally ACROSS the front. Those
    /// have no doctrinal meaning — a boundary parallel to the front is a rear
    /// boundary, not a lateral one. Instead the split is computed purely in the
    /// lateral coordinate, which can only ever produce rear-to-front lines.
    /// </summary>
    public class SectorSystem : MonoBehaviour
    {
        /// <summary>How far behind the rearmost unit the sector extends, km.</summary>
        const double RearDepthKm = 3.0;
        /// <summary>How far past the foremost unit boundaries run (the forward boundary), km.</summary>
        const double ForwardDepthKm = 4.0;
        /// <summary>Units within this fraction of the depth spread of the front count as the main battle area.</summary>
        const double ForwardBandFraction = 0.45;
        /// <summary>Minimum depth band, so a perfectly-aligned line of units still qualifies, km.</summary>
        const double MinForwardBandKm = 1.5;
        /// <summary>How far forward of its units the FEBA is drawn, km.</summary>
        const double FebaStandoffKm = 0.8;
        const int BoundarySamples = 5;

        public bool AutoUpdate;

        LineManager _lines;
        CesiumGeoreference _geo;
        readonly List<MapLabel> _labels = new List<MapLabel>();
        float _timer;
        bool _dirty;

        public void Init(LineManager lines, CesiumGeoreference geo)
        {
            _lines = lines;
            _geo = geo;
            UnitRegistry.Changed += MarkDirty;
        }

        void OnDestroy() => UnitRegistry.Changed -= MarkDirty;

        void MarkDirty() => _dirty = true;

        void Update()
        {
            if (!AutoUpdate || !_dirty) return;
            _timer += Time.deltaTime;
            if (_timer < GameConfig.FrontlineUpdateSeconds) return;
            _timer = 0f;
            _dirty = false;
            GenerateAll();
        }

        public void GenerateAll()
        {
            Generate(Team.User);
            Generate(Team.Enemy);
        }

        public void ClearAll()
        {
            _lines.RemoveAutoGenerated("sector-");
            foreach (var l in _labels) if (l != null) Destroy(l.gameObject);
            _labels.Clear();
        }

        // ------------------------------------------------------- generation

        /// <summary>
        /// Builds the full control-measure set for one side. Returns how many
        /// lines were produced (0 when the side has nothing to organise).
        /// </summary>
        public int Generate(Team team)
        {
            ClearFor(team);

            var own = AliveOf(team);
            var enemy = AliveOf(team == Team.User ? Team.Enemy : Team.User);
            if (own.Count == 0) return 0;

            // Local planar frame centred on the side's centroid. All the sector
            // geometry below is planar; doing it in raw degrees would skew with
            // latitude and hand the eastern formations wider sectors.
            Centroid(own, out double originLat, out double originLon);

            var pos = new List<Vector2d>(own.Count);
            foreach (var u in own)
            {
                GeoUtils.ToLocalKm(originLat, originLon, u.State.latitude, u.State.longitude,
                    out double e, out double n);
                pos.Add(new Vector2d(e, n));
            }

            if (!FrontAxis(own, enemy, pos, originLat, originLon, out Vector2d fwd, out Vector2d lat))
                return 0;

            // Project every unit onto the two axes: s = position along the
            // front (frontage), d = position in depth.
            var slot = new List<Slot>(own.Count);
            for (int i = 0; i < own.Count; i++)
            {
                slot.Add(new Slot
                {
                    unit = own[i],
                    s = pos[i].Dot(lat),
                    d = pos[i].Dot(fwd)
                });
            }
            slot.Sort((a, b) => a.s.CompareTo(b.s));

            double minD = double.MaxValue, maxD = double.MinValue;
            foreach (var s in slot) { minD = System.Math.Min(minD, s.d); maxD = System.Math.Max(maxD, s.d); }

            int count = 0;
            count += BuildLateralBoundaries(team, slot, fwd, lat, originLat, originLon, minD, maxD);
            count += BuildFeba(team, slot, fwd, lat, originLat, originLon, maxD);
            count += BuildRearBoundary(team, slot, fwd, lat, originLat, originLon, minD);
            return count;
        }

        public void ClearFor(Team team)
        {
            _lines.RemoveAutoGenerated($"sector-{team}-");
            for (int i = _labels.Count - 1; i >= 0; i--)
            {
                var l = _labels[i];
                if (l == null) { _labels.RemoveAt(i); continue; }
                if (l.name.Contains($"-{team}-")) { Destroy(l.gameObject); _labels.RemoveAt(i); }
            }
        }

        /// <summary>
        /// One boundary between each laterally adjacent pair, placed at the
        /// power-weighted split of their frontage coordinates: a stronger
        /// formation is given the wider sector, which is why the split is not a
        /// plain midpoint.
        /// </summary>
        int BuildLateralBoundaries(Team team, List<Slot> slot, Vector2d fwd, Vector2d lat,
            double originLat, double originLon, double minD, double maxD)
        {
            if (slot.Count < 2) return 0;

            double rear = minD - RearDepthKm;
            double front = maxD + ForwardDepthKm;
            int made = 0;

            for (int i = 0; i < slot.Count - 1; i++)
            {
                var a = slot[i];
                var b = slot[i + 1];

                float wa = Mathf.Max(1f, a.unit.CurrentPower());
                float wb = Mathf.Max(1f, b.unit.CurrentPower());
                // Heavier formation pushes the boundary away from itself.
                double s = (wb * a.s + wa * b.s) / (wa + wb);

                var pts = new List<GeoPoint>(BoundarySamples);
                for (int k = 0; k < BoundarySamples; k++)
                {
                    double t = k / (double)(BoundarySamples - 1);
                    double d = rear + (front - rear) * t;
                    pts.Add(Point(originLat, originLon, fwd, lat, s, d));
                }

                string id = $"sector-{team}-lateral-{i}";
                _lines.Upsert(new MapLineData
                {
                    id = id,
                    kind = LineKind.LateralBoundary.ToString(),
                    team = team.ToString(),
                    is3D = true,
                    autoGenerated = true,
                    points = pts,
                    echelon = LargerEchelon(a.unit, b.unit),
                    leftLabel = Designation(a.unit),
                    rightLabel = Designation(b.unit)
                });

                // Label group sits where the boundary crosses the FEBA, which
                // is where doctrine also places coordination points.
                var anchor = Point(originLat, originLon, fwd, lat, s, maxD + FebaStandoffKm);
                AddLabel($"sector-{team}-lateral-{i}",
                    $"{Designation(a.unit)}\n{LargerEchelon(a.unit, b.unit)}\n{Designation(b.unit)}",
                    TeamColor(team), anchor.latitude, anchor.longitude);
                made++;
            }
            return made;
        }

        /// <summary>
        /// FEBA through the forward formations only. Units echeloned well back
        /// are reserves, not the forward edge, so including them would drag the
        /// line rearward through the middle of the sector.
        /// </summary>
        int BuildFeba(Team team, List<Slot> slot, Vector2d fwd, Vector2d lat,
            double originLat, double originLon, double maxD)
        {
            double band = System.Math.Max(MinForwardBandKm,
                (maxD - MinDepth(slot)) * ForwardBandFraction);

            var forward = new List<Slot>();
            foreach (var s in slot) if (s.d >= maxD - band) forward.Add(s);
            if (forward.Count < 2) return 0;

            var raw = new List<GeoPoint>(forward.Count);
            foreach (var s in forward)
                raw.Add(Point(originLat, originLon, fwd, lat, s.s, s.d + FebaStandoffKm));

            var pts = Smooth(raw, 2);

            // Doctrine captions these lines at both ends. The caption travels in
            // the line's own `label` amplifier rather than as labels owned here,
            // so it is drawn by MapLine and survives a save/load.
            _lines.Upsert(new MapLineData
            {
                id = $"sector-{team}-feba",
                kind = LineKind.Feba.ToString(),
                team = team.ToString(),
                is3D = true,
                autoGenerated = true,
                points = pts,
                label = team == Team.Enemy ? "FEBA (ENY)" : "FEBA"
            });
            return 1;
        }

        int BuildRearBoundary(Team team, List<Slot> slot, Vector2d fwd, Vector2d lat,
            double originLat, double originLon, double minD)
        {
            if (slot.Count < 2) return 0;

            double d = minD - RearDepthKm;
            double sMin = slot[0].s - RearDepthKm;
            double sMax = slot[slot.Count - 1].s + RearDepthKm;

            var pts = new List<GeoPoint>
            {
                Point(originLat, originLon, fwd, lat, sMin, d),
                Point(originLat, originLon, fwd, lat, (sMin + sMax) * 0.5, d),
                Point(originLat, originLon, fwd, lat, sMax, d)
            };

            _lines.Upsert(new MapLineData
            {
                id = $"sector-{team}-rear",
                kind = LineKind.RearBoundary.ToString(),
                team = team.ToString(),
                is3D = true,
                autoGenerated = true,
                points = pts,
                // On a rear boundary the size marking is the subordinate's,
                // not the parent's (SS0529 §8b).
                echelon = SmallestEchelon(slot)
            });
            return 1;
        }

        // ------------------------------------------------------- axes

        /// <summary>
        /// Establishes the forward (depth) and lateral (frontage) axes.
        ///
        /// With enough units the lateral axis is the principal component of
        /// their positions — a deployed force lies along its own front, so the
        /// major eigenvector *is* the frontage direction, and this stays stable
        /// when the enemy is dispersed. With few or clustered units that
        /// estimate is unreliable, so the bearing to the enemy is used instead.
        /// Either way the enemy decides which way is "forward".
        /// </summary>
        bool FrontAxis(List<UnitActor> own, List<UnitActor> enemy, List<Vector2d> pos,
            double originLat, double originLon, out Vector2d fwd, out Vector2d lat)
        {
            fwd = new Vector2d(0, 1);
            lat = new Vector2d(1, 0);

            Vector2d toEnemy = default;
            bool haveEnemy = enemy.Count > 0;
            if (haveEnemy)
            {
                Centroid(enemy, out double eLat, out double eLon);
                GeoUtils.ToLocalKm(originLat, originLon, eLat, eLon, out double ee, out double en);
                toEnemy = new Vector2d(ee, en);
                if (toEnemy.Length < 1e-6) haveEnemy = false;
            }

            if (own.Count >= 4 && PrincipalAxis(pos, out Vector2d major))
            {
                lat = major.Normalized;
                fwd = new Vector2d(-lat.y, lat.x);          // rotate +90°
                if (haveEnemy && fwd.Dot(toEnemy) < 0) fwd = new Vector2d(-fwd.x, -fwd.y);
                // Keep the pair right-handed after any flip.
                lat = new Vector2d(fwd.y, -fwd.x);
                return true;
            }

            if (!haveEnemy) return false;                    // nothing to orient against
            fwd = toEnemy.Normalized;
            lat = new Vector2d(fwd.y, -fwd.x);
            return true;
        }

        /// <summary>Major eigenvector of the 2x2 covariance of the positions.</summary>
        static bool PrincipalAxis(List<Vector2d> pos, out Vector2d major)
        {
            major = default;
            int n = pos.Count;
            if (n < 2) return false;

            double mx = 0, my = 0;
            foreach (var p in pos) { mx += p.x; my += p.y; }
            mx /= n; my /= n;

            double sxx = 0, sxy = 0, syy = 0;
            foreach (var p in pos)
            {
                double dx = p.x - mx, dy = p.y - my;
                sxx += dx * dx; sxy += dx * dy; syy += dy * dy;
            }
            sxx /= n; sxy /= n; syy /= n;

            // Degenerate: all units effectively stacked.
            if (System.Math.Abs(sxx) + System.Math.Abs(syy) < 1e-9) return false;

            // Closed-form eigenvector for the larger eigenvalue.
            double tr = sxx + syy;
            double det = sxx * syy - sxy * sxy;
            double disc = System.Math.Sqrt(System.Math.Max(0.0, tr * tr / 4.0 - det));
            double eig = tr / 2.0 + disc;

            major = System.Math.Abs(sxy) > 1e-12
                ? new Vector2d(eig - syy, sxy)
                : (sxx >= syy ? new Vector2d(1, 0) : new Vector2d(0, 1));

            return major.Length > 1e-9;
        }

        // ------------------------------------------------------- helpers

        struct Slot
        {
            public UnitActor unit;
            public double s;    // frontage coordinate
            public double d;    // depth coordinate
        }

        /// <summary>Small double-precision 2-vector; the built-in Vector2 is float.</summary>
        struct Vector2d
        {
            public double x, y;
            public Vector2d(double x, double y) { this.x = x; this.y = y; }
            public double Dot(Vector2d o) => x * o.x + y * o.y;
            public double Length => System.Math.Sqrt(x * x + y * y);
            public Vector2d Normalized
            {
                get { double l = Length; return l < 1e-12 ? new Vector2d(0, 0) : new Vector2d(x / l, y / l); }
            }
        }

        static double MinDepth(List<Slot> slot)
        {
            double min = double.MaxValue;
            foreach (var s in slot) min = System.Math.Min(min, s.d);
            return min;
        }

        static List<UnitActor> AliveOf(Team team)
        {
            var result = new List<UnitActor>();
            foreach (var u in UnitRegistry.OfTeam(team))
                if (u != null && u.IsAlive) result.Add(u);
            return result;
        }

        static void Centroid(List<UnitActor> units, out double lat, out double lon)
        {
            lat = 0; lon = 0;
            if (units.Count == 0) return;
            foreach (var u in units) { lat += u.State.latitude; lon += u.State.longitude; }
            lat /= units.Count; lon /= units.Count;
        }

        /// <summary>Frontage/depth coordinates back to a geodetic point.</summary>
        static GeoPoint Point(double originLat, double originLon, Vector2d fwd, Vector2d lat,
            double s, double d)
        {
            double east = lat.x * s + fwd.x * d;
            double north = lat.y * s + fwd.y * d;
            GeoUtils.FromLocalKm(originLat, originLon, east, north, out double la, out double lo);
            return new GeoPoint { latitude = la, longitude = lo };
        }

        /// <summary>Chaikin corner-cutting, so the FEBA reads as a traced line not a zig-zag.</summary>
        static List<GeoPoint> Smooth(List<GeoPoint> pts, int iterations)
        {
            var current = pts;
            for (int it = 0; it < iterations && current.Count >= 3; it++)
            {
                var next = new List<GeoPoint> { current[0] };
                for (int i = 0; i < current.Count - 1; i++)
                {
                    var a = current[i];
                    var b = current[i + 1];
                    next.Add(Lerp(a, b, 0.25));
                    next.Add(Lerp(a, b, 0.75));
                }
                next.Add(current[current.Count - 1]);
                current = next;
            }
            return current;
        }

        static GeoPoint Lerp(GeoPoint a, GeoPoint b, double t) => new GeoPoint
        {
            latitude = a.latitude + (b.latitude - a.latitude) * t,
            longitude = a.longitude + (b.longitude - a.longitude) * t
        };

        static Color TeamColor(Team team) =>
            team == Team.Enemy ? GameConfig.RedTeam : GameConfig.BlueTeam;

        /// <summary>A lateral boundary carries the size of the larger of the two formations (SS0529 §8a).</summary>
        static string LargerEchelon(UnitActor a, UnitActor b)
        {
            var ea = a.State.EchelonEnum;
            var eb = b.State.EchelonEnum;
            return EchelonInfo.Indicator(ea >= eb ? ea : eb);
        }

        static string SmallestEchelon(List<Slot> slot)
        {
            Echelon smallest = Echelon.Army;
            foreach (var s in slot)
                if (s.unit.State.EchelonEnum < smallest) smallest = s.unit.State.EchelonEnum;
            return EchelonInfo.Indicator(smallest);
        }

        static string Designation(UnitActor u) =>
            string.IsNullOrEmpty(u.State.customName) ? u.Def.name : u.State.customName;

        void AddLabel(string id, string content, Color color, double lat, double lon)
        {
            var label = MapLabel.Create(_geo, transform, id);
            label.Set(content, color, lat, lon);
            _labels.Add(label);
        }
    }
}
